// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025-2026 Yurii Arkhanhelskyi
// Additional permission under AGPL-3.0 section 7: see LICENSE-EXCEPTION.
import 'dart:async';
import 'dart:io';

import 'package:ffmpeg_kit_flutter_new/ffmpeg_kit.dart';
import 'package:ffmpeg_kit_flutter_new/return_code.dart';
import 'package:flutter/material.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';
import 'package:video_player/video_player.dart';
import 'widgets/broken_media_box.dart';

/// Result returned by [VideoTrimEditorScreen]: the (possibly re-encoded) output
/// path plus the final duration in milliseconds.
class VideoTrimEditorResult {
  const VideoTrimEditorResult({required this.path, required this.durationMs});

  final String path;
  final int durationMs;
}

/// Telegram-style post-capture video editor. Lets the user trim the clip by
/// duration (filmstrip with draggable handles) and crop the frame (resizable
/// rectangle) before sending. Exports through FFmpeg — trim-only uses a fast
/// stream copy, crop re-encodes with libx264.
class VideoTrimEditorScreen extends StatefulWidget {
  const VideoTrimEditorScreen({
    super.key,
    required this.sourcePath,
    required this.localize,
  });

  final String sourcePath;
  final String Function(String ru, String en) localize;

  @override
  State<VideoTrimEditorScreen> createState() => _VideoTrimEditorScreenState();
}

class _VideoTrimEditorScreenState extends State<VideoTrimEditorScreen> {
  VideoPlayerController? _controller;
  bool _ready = false;
  bool _exporting = false;
  String? _error;

  // Trim range, in milliseconds, relative to the source clip.
  int _durationMs = 0;
  int _startMs = 0;
  int _endMs = 0;
  static const int _minTrimMs = 1000;

  // Crop rectangle as fractions (0..1) of the displayed video area. Default is
  // the full frame (no crop).
  Rect _crop = const Rect.fromLTWH(0, 0, 1, 1);
  bool _cropMode = false;

  // Filmstrip thumbnails generated by FFmpeg.
  List<File> _frames = const <File>[];

  String _t(String ru, String en) => widget.localize(ru, en);

  bool get _hasCrop =>
      _crop.left > 0.001 ||
      _crop.top > 0.001 ||
      _crop.right < 0.999 ||
      _crop.bottom < 0.999;

  @override
  void initState() {
    super.initState();
    unawaited(_init());
  }

  @override
  void dispose() {
    _controller?.removeListener(_onTick);
    _controller?.dispose();
    super.dispose();
  }

  Future<void> _init() async {
    try {
      final controller = VideoPlayerController.file(File(widget.sourcePath));
      await controller.initialize();
      controller.addListener(_onTick);
      await controller.setLooping(false);
      final durMs = controller.value.duration.inMilliseconds;
      if (!mounted) {
        await controller.dispose();
        return;
      }
      setState(() {
        _controller = controller;
        _durationMs = durMs;
        _startMs = 0;
        _endMs = durMs;
        _ready = true;
      });
      unawaited(controller.play());
      unawaited(_generateFrames());
    } catch (_) {
      if (mounted) {
        setState(() => _error = _t('Не удалось открыть видео', 'Failed to open video'));
      }
    }
  }

  void _onTick() {
    final controller = _controller;
    if (controller == null || !controller.value.isInitialized) return;
    final pos = controller.value.position.inMilliseconds;
    // Loop strictly inside the trimmed range.
    if (pos >= _endMs - 40 || pos < _startMs - 40) {
      unawaited(controller.seekTo(Duration(milliseconds: _startMs)));
      if (controller.value.isPlaying) {
        // keep playing from start
      }
    }
    if (mounted) setState(() {});
  }

  Future<void> _generateFrames() async {
    try {
      final dir = await getTemporaryDirectory();
      final stamp = DateTime.now().millisecondsSinceEpoch;
      final outDir = Directory(p.join(dir.path, 'vtrim_$stamp'));
      await outDir.create(recursive: true);
      const count = 10;
      final durSec = (_durationMs / 1000).clamp(0.001, 100000.0);
      final interval = (durSec / count).clamp(0.04, 100000.0);
      final pattern = p.join(outDir.path, 'f_%03d.jpg');
      final cmd =
          "-y -i '${widget.sourcePath}' -vf \"fps=1/$interval,scale=-2:140\" "
          "-vsync vfr -q:v 5 '$pattern'";
      final session = await FFmpegKit.execute(cmd);
      final rc = await session.getReturnCode();
      if (!ReturnCode.isSuccess(rc)) return;
      final files = outDir
          .listSync()
          .whereType<File>()
          .where((f) => f.path.toLowerCase().endsWith('.jpg'))
          .toList()
        ..sort((a, b) => a.path.compareTo(b.path));
      if (!mounted) return;
      setState(() => _frames = files);
    } catch (_) {
      // Filmstrip is decorative — ignore failures, handles still work.
    }
  }

  void _togglePlay() {
    final controller = _controller;
    if (controller == null) return;
    setState(() {
      if (controller.value.isPlaying) {
        controller.pause();
      } else {
        if (controller.value.position.inMilliseconds >= _endMs - 60) {
          controller.seekTo(Duration(milliseconds: _startMs));
        }
        controller.play();
      }
    });
  }

  void _onTrimChanged(int startMs, int endMs) {
    final controller = _controller;
    setState(() {
      _startMs = startMs.clamp(0, _durationMs);
      _endMs = endMs.clamp(_startMs + _minTrimMs, _durationMs);
    });
    if (controller != null) {
      final pos = controller.value.position.inMilliseconds;
      if (pos < _startMs || pos > _endMs) {
        unawaited(controller.seekTo(Duration(milliseconds: _startMs)));
      }
    }
  }

  Future<void> _export() async {
    final controller = _controller;
    if (controller == null || _exporting) return;
    final trimmed = _startMs > 60 || _endMs < _durationMs - 60;
    final cropped = _hasCrop;

    // Nothing changed → return the original untouched.
    if (!trimmed && !cropped) {
      Navigator.of(context).pop(
        VideoTrimEditorResult(path: widget.sourcePath, durationMs: _durationMs),
      );
      return;
    }

    setState(() => _exporting = true);
    await controller.pause();
    try {
      final dir = await getTemporaryDirectory();
      final stamp = DateTime.now().millisecondsSinceEpoch;
      final outPath = p.join(dir.path, 'vedit_$stamp.mp4');
      final startSec = (_startMs / 1000).toStringAsFixed(3);
      final durSec = ((_endMs - _startMs) / 1000).clamp(0.1, 100000.0)
          .toStringAsFixed(3);

      String cmd;
      if (cropped) {
        // Map the fractional crop onto the oriented frame (FFmpeg auto-rotates
        // by default, matching what video_player displays). Even dimensions are
        // required for yuv420p.
        final size = controller.value.size;
        final vw = size.width;
        final vh = size.height;
        int even(double v) {
          var i = v.round();
          if (i.isOdd) i -= 1;
          return i < 2 ? 2 : i;
        }

        final cw = even(_crop.width * vw);
        final ch = even(_crop.height * vh);
        final cx = (_crop.left * vw).round().clamp(0, (vw - cw).round());
        final cy = (_crop.top * vh).round().clamp(0, (vh - ch).round());
        cmd =
            "-y -ss $startSec -i '${widget.sourcePath}' -t $durSec "
            "-vf \"crop=$cw:$ch:$cx:$cy\" "
            "-c:v libx264 -preset veryfast -crf 23 -pix_fmt yuv420p "
            "-c:a aac -b:a 128k -movflags +faststart '$outPath'";
      } else {
        // Trim only → fast, lossless stream copy preserving rotation metadata.
        cmd =
            "-y -ss $startSec -i '${widget.sourcePath}' -t $durSec "
            "-c copy -movflags +faststart '$outPath'";
      }

      final session = await FFmpegKit.execute(cmd);
      final rc = await session.getReturnCode();
      final outFile = File(outPath);
      if (ReturnCode.isSuccess(rc) && outFile.existsSync() &&
          outFile.lengthSync() > 0) {
        if (!mounted) return;
        Navigator.of(context).pop(
          VideoTrimEditorResult(
            path: outPath,
            durationMs: _endMs - _startMs,
          ),
        );
        return;
      }
      // Fallback: if a trim-only stream copy failed (e.g. odd container), retry
      // by re-encoding before giving up.
      if (!cropped) {
        final reenc =
            "-y -ss $startSec -i '${widget.sourcePath}' -t $durSec "
            "-c:v libx264 -preset veryfast -crf 23 -pix_fmt yuv420p "
            "-c:a aac -b:a 128k -movflags +faststart '$outPath'";
        final s2 = await FFmpegKit.execute(reenc);
        final rc2 = await s2.getReturnCode();
        if (ReturnCode.isSuccess(rc2) && outFile.existsSync() &&
            outFile.lengthSync() > 0) {
          if (!mounted) return;
          Navigator.of(context).pop(
            VideoTrimEditorResult(
              path: outPath,
              durationMs: _endMs - _startMs,
            ),
          );
          return;
        }
      }
      throw Exception('export failed');
    } catch (_) {
      if (!mounted) return;
      setState(() {
        _exporting = false;
        _error = _t('Не удалось обработать видео', 'Failed to process video');
      });
    }
  }

  String _formatDuration(int ms) {
    final total = (ms / 1000).round();
    final m = total ~/ 60;
    final s = total % 60;
    return '$m:${s.toString().padLeft(2, '0')}';
  }

  @override
  Widget build(BuildContext context) {
    final controller = _controller;
    final media = MediaQuery.of(context);
    return Scaffold(
      backgroundColor: Colors.black,
      body: Stack(
        children: <Widget>[
          if (!_ready || controller == null)
            Center(
              child: _error != null
                  ? Text(_error!, style: const TextStyle(color: Colors.white70))
                  : const CircularProgressIndicator(color: Colors.white),
            )
          else
            Column(
              children: <Widget>[
                SizedBox(height: media.padding.top + 4),
                _buildTopBar(controller),
                Expanded(
                  child: Center(
                    child: AspectRatio(
                      aspectRatio: controller.value.aspectRatio == 0
                          ? 1
                          : controller.value.aspectRatio,
                      child: Stack(
                        fit: StackFit.expand,
                        children: <Widget>[
                          GestureDetector(
                            onTap: _cropMode ? null : _togglePlay,
                            child: VideoPlayer(controller),
                          ),
                          if (_cropMode)
                            _CropOverlay(
                              crop: _crop,
                              onChanged: (r) => setState(() => _crop = r),
                            ),
                          if (!_cropMode && !controller.value.isPlaying)
                            const Center(
                              child: _PlayBadge(),
                            ),
                        ],
                      ),
                    ),
                  ),
                ),
                _buildTrimBar(),
                SizedBox(height: media.padding.bottom + 10),
              ],
            ),
          if (_exporting)
            Positioned.fill(
              child: ColoredBox(
                color: Colors.black.withValues(alpha: 0.6),
                child: Center(
                  child: Column(
                    mainAxisSize: MainAxisSize.min,
                    children: <Widget>[
                      const CircularProgressIndicator(color: Colors.white),
                      const SizedBox(height: 16),
                      Text(
                        _t('Обработка видео…', 'Processing video…'),
                        style: const TextStyle(color: Colors.white),
                      ),
                    ],
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildTopBar(VideoPlayerController controller) {
    final selMs = _endMs - _startMs;
    return Padding(
      padding: const EdgeInsets.symmetric(horizontal: 8),
      child: Row(
        children: <Widget>[
          IconButton(
            onPressed: _exporting ? null : () => Navigator.of(context).pop(),
            icon: const Icon(Icons.close, color: Colors.white),
          ),
          const Spacer(),
          Text(
            _formatDuration(selMs),
            style: const TextStyle(
              color: Colors.white,
              fontWeight: FontWeight.w700,
              fontSize: 15,
            ),
          ),
          const Spacer(),
          IconButton(
            tooltip: _t('Кадрировать', 'Crop'),
            onPressed: _exporting
                ? null
                : () => setState(() => _cropMode = !_cropMode),
            icon: Icon(
              Icons.crop,
              color: _cropMode ? Theme.of(context).colorScheme.primary
                  : Colors.white,
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTrimBar() {
    return Padding(
      padding: const EdgeInsets.fromLTRB(16, 8, 16, 4),
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: <Widget>[
          VideoTrimTrack(
            durationMs: _durationMs,
            startMs: _startMs,
            endMs: _endMs,
            minTrimMs: _minTrimMs,
            frames: _frames,
            positionMs: _controller?.value.position.inMilliseconds ?? 0,
            onChanged: _onTrimChanged,
          ),
          const SizedBox(height: 16),
          Row(
            children: <Widget>[
              IconButton(
                onPressed: _togglePlay,
                icon: Icon(
                  (_controller?.value.isPlaying ?? false)
                      ? Icons.pause
                      : Icons.play_arrow,
                  color: Colors.white,
                  size: 30,
                ),
              ),
              const Spacer(),
              _SendButton(
                onTap: _exporting ? null : _export,
                label: _t('Отправить', 'Send'),
              ),
            ],
          ),
        ],
      ),
    );
  }
}

class _PlayBadge extends StatelessWidget {
  const _PlayBadge();

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 64,
      height: 64,
      decoration: BoxDecoration(
        color: Colors.black.withValues(alpha: 0.45),
        shape: BoxShape.circle,
      ),
      child: const Icon(Icons.play_arrow, color: Colors.white, size: 40),
    );
  }
}

class _SendButton extends StatelessWidget {
  const _SendButton({required this.onTap, required this.label});

  final VoidCallback? onTap;
  final String label;

  @override
  Widget build(BuildContext context) {
    final accent = Theme.of(context).colorScheme.primary;
    return Material(
      color: Colors.transparent,
      child: InkWell(
        borderRadius: BorderRadius.circular(24),
        onTap: onTap,
        child: Container(
          padding: const EdgeInsets.symmetric(horizontal: 22, vertical: 11),
          decoration: BoxDecoration(
            color: accent,
            borderRadius: BorderRadius.circular(24),
          ),
          child: Row(
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Text(
                label,
                style: const TextStyle(
                  color: Colors.white,
                  fontWeight: FontWeight.w700,
                  fontSize: 15,
                ),
              ),
              const SizedBox(width: 8),
              const Icon(Icons.send, color: Colors.white, size: 18),
            ],
          ),
        ),
      ),
    );
  }
}

/// Filmstrip + dual trim handles. Reports the selected [startMs] / [endMs].
class VideoTrimTrack extends StatelessWidget {
  const VideoTrimTrack({
    super.key,
    required this.durationMs,
    required this.startMs,
    required this.endMs,
    required this.minTrimMs,
    required this.frames,
    required this.positionMs,
    required this.onChanged,
  });

  final int durationMs;
  final int startMs;
  final int endMs;
  final int minTrimMs;
  final List<File> frames;
  final int positionMs;
  final void Function(int startMs, int endMs) onChanged;

  static const double _handleW = 14;
  static const double _trackH = 56;

  @override
  Widget build(BuildContext context) {
    final accent = Theme.of(context).colorScheme.primary;
    return LayoutBuilder(
      builder: (context, constraints) {
        final fullW = constraints.maxWidth;
        final usableW = (fullW - _handleW * 2).clamp(1.0, double.infinity);
        double msToX(int ms) =>
            _handleW + (durationMs == 0 ? 0 : ms / durationMs) * usableW;
        int xToMs(double x) =>
            (((x - _handleW) / usableW) * durationMs).round().clamp(0, durationMs);

        final startX = msToX(startMs);
        final endX = msToX(endMs);
        final playX = msToX(positionMs.clamp(startMs, endMs));

        return SizedBox(
          height: _trackH,
          width: fullW,
          child: Stack(
            children: <Widget>[
              // Filmstrip.
              Positioned(
                left: _handleW,
                right: _handleW,
                top: 0,
                bottom: 0,
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(8),
                  child: frames.isEmpty
                      ? Container(color: Colors.white10)
                      : Row(
                          children: <Widget>[
                            for (final f in frames)
                              Expanded(
                                child: Image.file(
                                  f,
                                  fit: BoxFit.cover,
                                  height: _trackH,
                                  gaplessPlayback: true,
                                  errorBuilder: (_, _, _) => const BrokenMediaBox(iconSize: 12, onDarkSurface: true),
                                ),
                              ),
                          ],
                        ),
                ),
              ),
              // Dim the trimmed-away regions.
              Positioned(
                left: _handleW,
                width: (startX - _handleW).clamp(0.0, usableW),
                top: 0,
                bottom: 0,
                child: const ColoredBox(color: Color(0x99000000)),
              ),
              Positioned(
                left: endX,
                right: _handleW,
                top: 0,
                bottom: 0,
                child: const ColoredBox(color: Color(0x99000000)),
              ),
              // Selection border.
              Positioned(
                left: startX,
                width: (endX - startX).clamp(0.0, fullW),
                top: 0,
                bottom: 0,
                child: DecoratedBox(
                  decoration: BoxDecoration(
                    border: Border.symmetric(
                      horizontal: BorderSide(color: accent, width: 2.5),
                    ),
                  ),
                ),
              ),
              // Playhead.
              Positioned(
                left: playX - 1,
                top: 2,
                bottom: 2,
                child: Container(width: 2, color: Colors.white),
              ),
              // Left handle.
              _buildHandle(
                left: startX - _handleW,
                accent: accent,
                isLeft: true,
                onDrag: (dx) {
                  final newStart = xToMs(startX + dx);
                  onChanged(
                    newStart.clamp(0, endMs - minTrimMs),
                    endMs,
                  );
                },
              ),
              // Right handle.
              _buildHandle(
                left: endX,
                accent: accent,
                isLeft: false,
                onDrag: (dx) {
                  final newEnd = xToMs(endX + dx);
                  onChanged(
                    startMs,
                    newEnd.clamp(startMs + minTrimMs, durationMs),
                  );
                },
              ),
            ],
          ),
        );
      },
    );
  }

  Widget _buildHandle({
    required double left,
    required Color accent,
    required bool isLeft,
    required void Function(double dx) onDrag,
  }) {
    return Positioned(
      left: left,
      top: 0,
      bottom: 0,
      width: _handleW,
      child: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onHorizontalDragUpdate: (d) => onDrag(d.delta.dx),
        child: Container(
          decoration: BoxDecoration(
            color: accent,
            borderRadius: BorderRadius.horizontal(
              left: isLeft ? const Radius.circular(8) : Radius.zero,
              right: isLeft ? Radius.zero : const Radius.circular(8),
            ),
          ),
          child: const Center(
            child: Icon(Icons.drag_indicator, color: Colors.white, size: 14),
          ),
        ),
      ),
    );
  }
}

/// Resizable crop rectangle drawn over the video. [crop] is fractional (0..1)
/// of the displayed video area.
class _CropOverlay extends StatelessWidget {
  const _CropOverlay({required this.crop, required this.onChanged});

  final Rect crop;
  final ValueChanged<Rect> onChanged;

  static const double _min = 0.12;

  @override
  Widget build(BuildContext context) {
    final accent = Theme.of(context).colorScheme.primary;
    return LayoutBuilder(
      builder: (context, constraints) {
        final w = constraints.maxWidth;
        final h = constraints.maxHeight;
        final rect = Rect.fromLTRB(
          crop.left * w,
          crop.top * h,
          crop.right * w,
          crop.bottom * h,
        );

        Rect clampFrac(Rect r) {
          var l = r.left.clamp(0.0, 1.0 - _min);
          var t = r.top.clamp(0.0, 1.0 - _min);
          var rr = r.right.clamp(l + _min, 1.0);
          var bb = r.bottom.clamp(t + _min, 1.0);
          return Rect.fromLTRB(l, t, rr, bb);
        }

        void moveBody(Offset delta) {
          final dx = delta.dx / w;
          final dy = delta.dy / h;
          var l = crop.left + dx;
          var t = crop.top + dy;
          final cw = crop.width;
          final ch = crop.height;
          l = l.clamp(0.0, 1.0 - cw);
          t = t.clamp(0.0, 1.0 - ch);
          onChanged(Rect.fromLTWH(l, t, cw, ch));
        }

        void dragCorner(Offset delta, {required bool left, required bool top}) {
          final dx = delta.dx / w;
          final dy = delta.dy / h;
          var l = crop.left;
          var t = crop.top;
          var r = crop.right;
          var b = crop.bottom;
          if (left) {
            l += dx;
          } else {
            r += dx;
          }
          if (top) {
            t += dy;
          } else {
            b += dy;
          }
          onChanged(clampFrac(Rect.fromLTRB(l, t, r, b)));
        }

        const handle = 28.0;
        return Stack(
          children: <Widget>[
            // Dim outside the crop.
            IgnorePointer(
              child: CustomPaint(
                size: Size(w, h),
                painter: _CropDimPainter(rect: rect, accent: accent),
              ),
            ),
            // Body drag.
            Positioned.fromRect(
              rect: rect,
              child: GestureDetector(
                behavior: HitTestBehavior.translucent,
                onPanUpdate: (d) => moveBody(d.delta),
              ),
            ),
            _corner(rect.topLeft, handle,
                (d) => dragCorner(d, left: true, top: true)),
            _corner(rect.topRight, handle,
                (d) => dragCorner(d, left: false, top: true)),
            _corner(rect.bottomLeft, handle,
                (d) => dragCorner(d, left: true, top: false)),
            _corner(rect.bottomRight, handle,
                (d) => dragCorner(d, left: false, top: false)),
          ],
        );
      },
    );
  }

  Widget _corner(Offset center, double size, ValueChanged<Offset> onDrag) {
    return Positioned(
      left: center.dx - size / 2,
      top: center.dy - size / 2,
      width: size,
      height: size,
      child: GestureDetector(
        behavior: HitTestBehavior.opaque,
        onPanUpdate: (d) => onDrag(d.delta),
        child: const SizedBox.expand(),
      ),
    );
  }
}

class _CropDimPainter extends CustomPainter {
  _CropDimPainter({required this.rect, required this.accent});

  final Rect rect;
  final Color accent;

  @override
  void paint(Canvas canvas, Size size) {
    final full = Offset.zero & size;
    final dim = Paint()..color = Colors.black.withValues(alpha: 0.45);
    final outside = Path()
      ..addRect(full)
      ..addRect(rect)
      ..fillType = PathFillType.evenOdd;
    canvas.drawPath(outside, dim);

    final border = Paint()
      ..color = Colors.white
      ..style = PaintingStyle.stroke
      ..strokeWidth = 2;
    canvas.drawRect(rect, border);

    // Rule-of-thirds grid.
    final grid = Paint()
      ..color = Colors.white.withValues(alpha: 0.35)
      ..strokeWidth = 1;
    for (var i = 1; i < 3; i++) {
      final dx = rect.left + rect.width * i / 3;
      canvas.drawLine(Offset(dx, rect.top), Offset(dx, rect.bottom), grid);
      final dy = rect.top + rect.height * i / 3;
      canvas.drawLine(Offset(rect.left, dy), Offset(rect.right, dy), grid);
    }

    // Corner accents.
    final corner = Paint()
      ..color = accent
      ..style = PaintingStyle.stroke
      ..strokeWidth = 4
      ..strokeCap = StrokeCap.round;
    const len = 18.0;
    void drawCorner(Offset c, double sx, double sy) {
      canvas.drawLine(c, c.translate(sx * len, 0), corner);
      canvas.drawLine(c, c.translate(0, sy * len), corner);
    }

    drawCorner(rect.topLeft, 1, 1);
    drawCorner(rect.topRight, -1, 1);
    drawCorner(rect.bottomLeft, 1, -1);
    drawCorner(rect.bottomRight, -1, -1);
  }

  @override
  bool shouldRepaint(_CropDimPainter old) =>
      old.rect != rect || old.accent != accent;
}


/// TELEGRAM SEND EDITOR (2026-07-17): shared helpers so the gallery pre-send
/// editor reuses this screen's proven FFmpeg pipeline.
///
/// Filmstrip frames for a trim track — small JPEGs in a temp dir.
Future<List<File>> videoTrimFilmstripFrames(
  String sourcePath, {
  int count = 12,
  int heightPx = 120,
}) async {
  try {
    final dir = await getTemporaryDirectory();
    final stamp = DateTime.now().millisecondsSinceEpoch;
    final outDir = Directory(p.join(dir.path, 'vstrip_$stamp'));
    await outDir.create(recursive: true);
    // Probe-free: rely on fps sampling across the whole clip.
    final pattern = p.join(outDir.path, 'f_%03d.jpg');
    final cmd =
        "-y -i '$sourcePath' -vf \"select='not(mod(n\\,max(1\\,floor(n_frames/$count))))',scale=-2:$heightPx\" "
        "-vsync vfr -frames:v $count -q:v 5 '$pattern'";
    var session = await FFmpegKit.execute(cmd);
    var rc = await session.getReturnCode();
    if (!ReturnCode.isSuccess(rc)) {
      // Fallback: time-based sampling (n_frames unavailable in some containers).
      final cmd2 =
          "-y -i '$sourcePath' -vf \"fps=$count/10,scale=-2:$heightPx\" "
          "-vsync vfr -frames:v $count -q:v 5 '$pattern'";
      session = await FFmpegKit.execute(cmd2);
      rc = await session.getReturnCode();
      if (!ReturnCode.isSuccess(rc)) return const <File>[];
    }
    final files =
        outDir
            .listSync()
            .whereType<File>()
            .where((f) => f.path.toLowerCase().endsWith('.jpg'))
            .toList()
          ..sort((a, b) => a.path.compareTo(b.path));
    return files;
  } catch (_) {
    return const <File>[];
  }
}

/// Fast trim-only export (stream copy, re-encode fallback). Returns the new
/// file path, or null on failure.
Future<String?> exportTrimmedVideoFile(
  String sourcePath, {
  required int startMs,
  required int endMs,
}) async {
  try {
    final dir = await getTemporaryDirectory();
    final stamp = DateTime.now().millisecondsSinceEpoch;
    final outPath = p.join(dir.path, 'vsend_$stamp.mp4');
    final startSec = (startMs / 1000).toStringAsFixed(3);
    final durSec = ((endMs - startMs) / 1000)
        .clamp(0.1, 100000.0)
        .toStringAsFixed(3);
    final copyCmd =
        "-y -ss $startSec -i '$sourcePath' -t $durSec "
        "-c copy -movflags +faststart '$outPath'";
    var session = await FFmpegKit.execute(copyCmd);
    var rc = await session.getReturnCode();
    final outFile = File(outPath);
    if (ReturnCode.isSuccess(rc) &&
        outFile.existsSync() &&
        outFile.lengthSync() > 0) {
      return outPath;
    }
    final reencCmd =
        "-y -ss $startSec -i '$sourcePath' -t $durSec "
        "-c:v libx264 -preset veryfast -crf 23 -pix_fmt yuv420p "
        "-c:a aac -b:a 128k -movflags +faststart '$outPath'";
    session = await FFmpegKit.execute(reencCmd);
    rc = await session.getReturnCode();
    if (ReturnCode.isSuccess(rc) &&
        outFile.existsSync() &&
        outFile.lengthSync() > 0) {
      return outPath;
    }
    return null;
  } catch (_) {
    return null;
  }
}
