// SPDX-License-Identifier: AGPL-3.0-only
// SPDX-FileCopyrightText: 2025-2026 Yurii Arkhanhelskyi
// Additional permission under AGPL-3.0 section 7: see LICENSE-EXCEPTION.
// Desktop port of the mobile Noto-emoji-animation helper that lives in
// `lib/ui/chat_screen.dart` (PR3.7 + PR3.8 + PR3.9, 2026-05-19,
// SPRINT2_AUDIT §13 / §14).
//
// Mobile renders animated reactions and bubble-free «solo emoji» messages
// using Lottie JSON pulled from the Google Noto CDN
// (https://fonts.gstatic.com/s/e/notoemoji/latest/{codepoint}/lottie.json).
// The codepoint map and the loader are private (`_notoCodepoints`,
// `_loadNotoLottieFile`) inside `chat_screen.dart`, so the desktop side
// duplicates the table here rather than touching the mobile screen — the
// user has been explicit that the mobile design must not be modified in
// this sprint.
//
// PR3.8 (2026-05-19): the codepoint table has been expanded from ~90
// entries (mobile parity) to the FULL Noto Emoji Animation catalog from
// https://googlefonts.github.io/noto-emoji-animation/data/api.json (881
// entries — every animatable emoji including all skin-tone variants and
// ZWJ sequences). The mobile design will catch up over a separate PR; for
// now desktop simply has a strictly-larger known set, which is fine because
// the runtime gate is "key present in this map → render Lottie", with a
// safe text fallback otherwise.
//
// PR3.9 (2026-05-19): added category metadata so the expanded reactions
// picker can render Telegram-style category sections with a left-rail jump
// strip. The category slug for each emoji is read from the upstream
// manifest's `categories[0]` field, slugified to `lower_snake_case`. The
// nine slugs that appear in the current manifest are:
//
//   smileys_and_emotions, people, animals_and_nature, food_and_drink,
//   travel_and_places, activities_and_events, objects, symbols, flags
//
// `kDesktopNotoCategoryOrder` preserves first-appearance order from the
// manifest, and `kDesktopNotoCategoryLabelsRu` gives human-readable
// Russian display names for the picker section headers.
//
// Disk caching reuses the same `noto_emoji_{codepoint}.json` filename in
// the system temp dir, so once mobile downloads an emoji the desktop picks
// it up for free (and vice versa).

import 'dart:io';

import 'package:flutter/material.dart';
import 'package:http/http.dart' as http_pkg;
import 'package:visibility_detector/visibility_detector.dart';
import 'package:lottie/lottie.dart';
import 'package:path/path.dart' as p;
import 'package:path_provider/path_provider.dart';

import '../../emoji/noto_lottie_normalize.dart';

/// Noto Emoji Animation codepoints. Auto-imported from the upstream
/// manifest; do not edit by hand — re-run `tools/regen_noto_codepoints.py`
/// against the latest `api.json` to regenerate.
const Map<String, String> kDesktopNotoCodepoints = <String, String>{
  '😀': '1f600',
  '😃': '1f603',
  '😄': '1f604',
  '😁': '1f601',
  '😆': '1f606',
  '😅': '1f605',
  '😂': '1f602',
  '🤣': '1f923',
  '😭': '1f62d',
  '😉': '1f609',
  '😗': '1f617',
  '😙': '1f619',
  '😚': '1f61a',
  '😘': '1f618',
  '🥰': '1f970',
  '😍': '1f60d',
  '🤩': '1f929',
  '🥳': '1f973',
  '🫠': '1fae0',
  '🙃': '1f643',
  '🙂': '1f642',
  '🥲': '1f972',
  '🥹': '1f979',
  '😊': '1f60a',
  '☺️': '263a_fe0f',
  '😌': '1f60c',
  '🙂‍↕️': '1f642_200d_2195_fe0f',
  '🙂‍↔️': '1f642_200d_2194_fe0f',
  '😏': '1f60f',
  '🤤': '1f924',
  '😋': '1f60b',
  '😛': '1f61b',
  '😝': '1f61d',
  '😜': '1f61c',
  '🤪': '1f92a',
  '🫪': '1faea',
  '😔': '1f614',
  '🥺': '1f97a',
  '😬': '1f62c',
  '😑': '1f611',
  '😐': '1f610',
  '😶': '1f636',
  '😶‍🌫️': '1f636_200d_1f32b_fe0f',
  '🫥': '1fae5',
  '🤐': '1f910',
  '🫡': '1fae1',
  '🤔': '1f914',
  '🤫': '1f92b',
  '🫢': '1fae2',
  '🤭': '1f92d',
  '🥱': '1f971',
  '🤗': '1f917',
  '🫣': '1fae3',
  '😱': '1f631',
  '🤨': '1f928',
  '🧐': '1f9d0',
  '😒': '1f612',
  '🙄': '1f644',
  '😮‍💨': '1f62e_200d_1f4a8',
  '😤': '1f624',
  '😠': '1f620',
  '😡': '1f621',
  '🤬': '1f92c',
  '😞': '1f61e',
  '😓': '1f613',
  '😟': '1f61f',
  '😥': '1f625',
  '😢': '1f622',
  '☹️': '2639_fe0f',
  '🙁': '1f641',
  '🫤': '1fae4',
  '😕': '1f615',
  '😰': '1f630',
  '😨': '1f628',
  '😧': '1f627',
  '😦': '1f626',
  '😮': '1f62e',
  '😯': '1f62f',
  '😲': '1f632',
  '😳': '1f633',
  '🤯': '1f92f',
  '😖': '1f616',
  '😣': '1f623',
  '😩': '1f629',
  '😫': '1f62b',
  '😵': '1f635',
  '😵‍💫': '1f635_200d_1f4ab',
  '🫨': '1fae8',
  '🥴': '1f974',
  '🥵': '1f975',
  '🥶': '1f976',
  '🤢': '1f922',
  '🤮': '1f92e',
  '🫩': '1fae9',
  '😴': '1f634',
  '😪': '1f62a',
  '🤧': '1f927',
  '🤒': '1f912',
  '🤕': '1f915',
  '😷': '1f637',
  '🤥': '1f925',
  '😇': '1f607',
  '🤠': '1f920',
  '🤑': '1f911',
  '🤓': '1f913',
  '😎': '1f60e',
  '🥸': '1f978',
  '🤡': '1f921',
  '💩': '1f4a9',
  '😈': '1f608',
  '👿': '1f47f',
  '👻': '1f47b',
  '💀': '1f480',
  '🤖': '1f916',
  '👹': '1f479',
  '☃️': '2603_fe0f',
  '⛄': '26c4',
  '👽': '1f47d',
  '👾': '1f47e',
  '🌚': '1f31a',
  '🌝': '1f31d',
  '🌞': '1f31e',
  '🌛': '1f31b',
  '🌜': '1f31c',
  '😺': '1f63a',
  '😸': '1f638',
  '😹': '1f639',
  '😻': '1f63b',
  '😼': '1f63c',
  '😽': '1f63d',
  '🙀': '1f640',
  '😿': '1f63f',
  '😾': '1f63e',
  '🙈': '1f648',
  '🙉': '1f649',
  '🙊': '1f64a',
  '⭐': '2b50',
  '🌟': '1f31f',
  '✨': '2728',
  '⚡': '26a1',
  '💥': '1f4a5',
  '🫯': '1faef',
  '🕳️': '1f573_fe0f',
  '🔥': '1f525',
  '💯': '1f4af',
  '🎉': '1f389',
  '🎊': '1f38a',
  '❤️': '2764_fe0f',
  '🧡': '1f9e1',
  '💛': '1f49b',
  '💚': '1f49a',
  '🩵': '1fa75',
  '💙': '1f499',
  '💜': '1f49c',
  '🤎': '1f90e',
  '🖤': '1f5a4',
  '🩶': '1fa76',
  '🤍': '1f90d',
  '🩷': '1fa77',
  '💘': '1f498',
  '💝': '1f49d',
  '💖': '1f496',
  '💗': '1f497',
  '💓': '1f493',
  '💞': '1f49e',
  '💕': '1f495',
  '💌': '1f48c',
  '💟': '1f49f',
  '♥️': '2665_fe0f',
  '❣️': '2763_fe0f',
  '❤️‍🩹': '2764_fe0f_200d_1fa79',
  '💔': '1f494',
  '❤️‍🔥': '2764_fe0f_200d_1f525',
  '💋': '1f48b',
  '🫂': '1fac2',
  '🗣️': '1f5e3_fe0f',
  '👣': '1f463',
  '🫆': '1fac6',
  '🧠': '1f9e0',
  '🫀': '1fac0',
  '🩸': '1fa78',
  '🦠': '1f9a0',
  '🦴': '1f9b4',
  '👀': '1f440',
  '👁️': '1f441_fe0f',
  '🫦': '1fae6',
  '👃': '1f443',
  '👃🏻': '1f443_1f3fb',
  '👃🏼': '1f443_1f3fc',
  '👃🏽': '1f443_1f3fd',
  '👃🏾': '1f443_1f3fe',
  '👃🏿': '1f443_1f3ff',
  '👂': '1f442',
  '👂🏻': '1f442_1f3fb',
  '👂🏼': '1f442_1f3fc',
  '👂🏽': '1f442_1f3fd',
  '👂🏾': '1f442_1f3fe',
  '👂🏿': '1f442_1f3ff',
  '🦻': '1f9bb',
  '🦻🏻': '1f9bb_1f3fb',
  '🦻🏼': '1f9bb_1f3fc',
  '🦻🏽': '1f9bb_1f3fd',
  '🦻🏾': '1f9bb_1f3fe',
  '🦻🏿': '1f9bb_1f3ff',
  '🦶': '1f9b6',
  '🦶🏻': '1f9b6_1f3fb',
  '🦶🏼': '1f9b6_1f3fc',
  '🦶🏽': '1f9b6_1f3fd',
  '🦶🏾': '1f9b6_1f3fe',
  '🦶🏿': '1f9b6_1f3ff',
  '🦵': '1f9b5',
  '🦵🏻': '1f9b5_1f3fb',
  '🦵🏼': '1f9b5_1f3fc',
  '🦵🏽': '1f9b5_1f3fd',
  '🦵🏾': '1f9b5_1f3fe',
  '🦵🏿': '1f9b5_1f3ff',
  '🦿': '1f9bf',
  '🦾': '1f9be',
  '💪': '1f4aa',
  '💪🏻': '1f4aa_1f3fb',
  '💪🏼': '1f4aa_1f3fc',
  '💪🏽': '1f4aa_1f3fd',
  '💪🏾': '1f4aa_1f3fe',
  '💪🏿': '1f4aa_1f3ff',
  '👏': '1f44f',
  '👏🏻': '1f44f_1f3fb',
  '👏🏼': '1f44f_1f3fc',
  '👏🏽': '1f44f_1f3fd',
  '👏🏾': '1f44f_1f3fe',
  '👏🏿': '1f44f_1f3ff',
  '👍': '1f44d',
  '👍🏻': '1f44d_1f3fb',
  '👍🏼': '1f44d_1f3fc',
  '👍🏽': '1f44d_1f3fd',
  '👍🏾': '1f44d_1f3fe',
  '👍🏿': '1f44d_1f3ff',
  '👎': '1f44e',
  '👎🏻': '1f44e_1f3fb',
  '👎🏼': '1f44e_1f3fc',
  '👎🏽': '1f44e_1f3fd',
  '👎🏾': '1f44e_1f3fe',
  '👎🏿': '1f44e_1f3ff',
  '🫶': '1faf6',
  '🫶🏻': '1faf6_1f3fb',
  '🫶🏼': '1faf6_1f3fc',
  '🫶🏽': '1faf6_1f3fd',
  '🫶🏾': '1faf6_1f3fe',
  '🫶🏿': '1faf6_1f3ff',
  '🙌': '1f64c',
  '🙌🏻': '1f64c_1f3fb',
  '🙌🏼': '1f64c_1f3fc',
  '🙌🏽': '1f64c_1f3fd',
  '🙌🏾': '1f64c_1f3fe',
  '🙌🏿': '1f64c_1f3ff',
  '👐': '1f450',
  '👐🏻': '1f450_1f3fb',
  '👐🏼': '1f450_1f3fc',
  '👐🏽': '1f450_1f3fd',
  '👐🏾': '1f450_1f3fe',
  '👐🏿': '1f450_1f3ff',
  '🤲': '1f932',
  '🤲🏻': '1f932_1f3fb',
  '🤲🏼': '1f932_1f3fc',
  '🤲🏽': '1f932_1f3fd',
  '🤲🏾': '1f932_1f3fe',
  '🤲🏿': '1f932_1f3ff',
  '🤜': '1f91c',
  '🤜🏻': '1f91c_1f3fb',
  '🤜🏼': '1f91c_1f3fc',
  '🤜🏽': '1f91c_1f3fd',
  '🤜🏾': '1f91c_1f3fe',
  '🤜🏿': '1f91c_1f3ff',
  '🤛': '1f91b',
  '🤛🏻': '1f91b_1f3fb',
  '🤛🏼': '1f91b_1f3fc',
  '🤛🏽': '1f91b_1f3fd',
  '🤛🏾': '1f91b_1f3fe',
  '🤛🏿': '1f91b_1f3ff',
  '✊': '270a',
  '✊🏻': '270a_1f3fb',
  '✊🏼': '270a_1f3fc',
  '✊🏽': '270a_1f3fd',
  '✊🏾': '270a_1f3fe',
  '✊🏿': '270a_1f3ff',
  '👊': '1f44a',
  '👊🏻': '1f44a_1f3fb',
  '👊🏼': '1f44a_1f3fc',
  '👊🏽': '1f44a_1f3fd',
  '👊🏾': '1f44a_1f3fe',
  '👊🏿': '1f44a_1f3ff',
  '🫳': '1faf3',
  '🫳🏻': '1faf3_1f3fb',
  '🫳🏼': '1faf3_1f3fc',
  '🫳🏽': '1faf3_1f3fd',
  '🫳🏾': '1faf3_1f3fe',
  '🫳🏿': '1faf3_1f3ff',
  '🫴': '1faf4',
  '🫴🏻': '1faf4_1f3fb',
  '🫴🏼': '1faf4_1f3fc',
  '🫴🏽': '1faf4_1f3fd',
  '🫴🏾': '1faf4_1f3fe',
  '🫴🏿': '1faf4_1f3ff',
  '🫱': '1faf1',
  '🫱🏻': '1faf1_1f3fb',
  '🫱🏼': '1faf1_1f3fc',
  '🫱🏽': '1faf1_1f3fd',
  '🫱🏾': '1faf1_1f3fe',
  '🫱🏿': '1faf1_1f3ff',
  '🫲': '1faf2',
  '🫲🏻': '1faf2_1f3fb',
  '🫲🏼': '1faf2_1f3fc',
  '🫲🏽': '1faf2_1f3fd',
  '🫲🏾': '1faf2_1f3fe',
  '🫲🏿': '1faf2_1f3ff',
  '🫸': '1faf8',
  '🫸🏻': '1faf8_1f3fb',
  '🫸🏼': '1faf8_1f3fc',
  '🫸🏽': '1faf8_1f3fd',
  '🫸🏾': '1faf8_1f3fe',
  '🫸🏿': '1faf8_1f3ff',
  '🫷': '1faf7',
  '🫷🏻': '1faf7_1f3fb',
  '🫷🏼': '1faf7_1f3fc',
  '🫷🏽': '1faf7_1f3fd',
  '🫷🏾': '1faf7_1f3fe',
  '🫷🏿': '1faf7_1f3ff',
  '👋': '1f44b',
  '👋🏻': '1f44b_1f3fb',
  '👋🏼': '1f44b_1f3fc',
  '👋🏽': '1f44b_1f3fd',
  '👋🏾': '1f44b_1f3fe',
  '👋🏿': '1f44b_1f3ff',
  '🤚': '1f91a',
  '🤚🏻': '1f91a_1f3fb',
  '🤚🏼': '1f91a_1f3fc',
  '🤚🏽': '1f91a_1f3fd',
  '🤚🏾': '1f91a_1f3fe',
  '🤚🏿': '1f91a_1f3ff',
  '🖐️': '1f590_fe0f',
  '🖐🏻': '1f590_1f3fb',
  '🖐🏼': '1f590_1f3fc',
  '🖐🏽': '1f590_1f3fd',
  '🖐🏾': '1f590_1f3fe',
  '🖐🏿': '1f590_1f3ff',
  '✋': '270b',
  '✋🏻': '270b_1f3fb',
  '✋🏼': '270b_1f3fc',
  '✋🏽': '270b_1f3fd',
  '✋🏾': '270b_1f3fe',
  '✋🏿': '270b_1f3ff',
  '🖖': '1f596',
  '🖖🏻': '1f596_1f3fb',
  '🖖🏼': '1f596_1f3fc',
  '🖖🏽': '1f596_1f3fd',
  '🖖🏾': '1f596_1f3fe',
  '🖖🏿': '1f596_1f3ff',
  '🤟': '1f91f',
  '🤟🏻': '1f91f_1f3fb',
  '🤟🏼': '1f91f_1f3fc',
  '🤟🏽': '1f91f_1f3fd',
  '🤟🏾': '1f91f_1f3fe',
  '🤟🏿': '1f91f_1f3ff',
  '🤘': '1f918',
  '🤘🏻': '1f918_1f3fb',
  '🤘🏼': '1f918_1f3fc',
  '🤘🏽': '1f918_1f3fd',
  '🤘🏾': '1f918_1f3fe',
  '🤘🏿': '1f918_1f3ff',
  '✌️': '270c_fe0f',
  '✌🏻': '270c_1f3fb',
  '✌🏼': '270c_1f3fc',
  '✌🏽': '270c_1f3fd',
  '✌🏾': '270c_1f3fe',
  '✌🏿': '270c_1f3ff',
  '🤞': '1f91e',
  '🤞🏻': '1f91e_1f3fb',
  '🤞🏼': '1f91e_1f3fc',
  '🤞🏽': '1f91e_1f3fd',
  '🤞🏾': '1f91e_1f3fe',
  '🤞🏿': '1f91e_1f3ff',
  '🫰': '1faf0',
  '🫰🏻': '1faf0_1f3fb',
  '🫰🏼': '1faf0_1f3fc',
  '🫰🏽': '1faf0_1f3fd',
  '🫰🏾': '1faf0_1f3fe',
  '🫰🏿': '1faf0_1f3ff',
  '🤙': '1f919',
  '🤙🏻': '1f919_1f3fb',
  '🤙🏼': '1f919_1f3fc',
  '🤙🏽': '1f919_1f3fd',
  '🤙🏾': '1f919_1f3fe',
  '🤙🏿': '1f919_1f3ff',
  '🤌': '1f90c',
  '🤌🏻': '1f90c_1f3fb',
  '🤌🏼': '1f90c_1f3fc',
  '🤌🏽': '1f90c_1f3fd',
  '🤌🏾': '1f90c_1f3fe',
  '🤌🏿': '1f90c_1f3ff',
  '🤏': '1f90f',
  '🤏🏻': '1f90f_1f3fb',
  '🤏🏼': '1f90f_1f3fc',
  '🤏🏽': '1f90f_1f3fd',
  '🤏🏾': '1f90f_1f3fe',
  '🤏🏿': '1f90f_1f3ff',
  '👌': '1f44c',
  '👌🏻': '1f44c_1f3fb',
  '👌🏼': '1f44c_1f3fc',
  '👌🏽': '1f44c_1f3fd',
  '👌🏾': '1f44c_1f3fe',
  '👌🏿': '1f44c_1f3ff',
  '🫵': '1faf5',
  '🫵🏻': '1faf5_1f3fb',
  '🫵🏼': '1faf5_1f3fc',
  '🫵🏽': '1faf5_1f3fd',
  '🫵🏾': '1faf5_1f3fe',
  '🫵🏿': '1faf5_1f3ff',
  '👉': '1f449',
  '👉🏻': '1f449_1f3fb',
  '👉🏼': '1f449_1f3fc',
  '👉🏽': '1f449_1f3fd',
  '👉🏾': '1f449_1f3fe',
  '👉🏿': '1f449_1f3ff',
  '👈': '1f448',
  '👈🏻': '1f448_1f3fb',
  '👈🏼': '1f448_1f3fc',
  '👈🏽': '1f448_1f3fd',
  '👈🏾': '1f448_1f3fe',
  '👈🏿': '1f448_1f3ff',
  '☝️': '261d_fe0f',
  '☝🏻': '261d_1f3fb',
  '☝🏼': '261d_1f3fc',
  '☝🏽': '261d_1f3fd',
  '☝🏾': '261d_1f3fe',
  '☝🏿': '261d_1f3ff',
  '👆': '1f446',
  '👆🏻': '1f446_1f3fb',
  '👆🏼': '1f446_1f3fc',
  '👆🏽': '1f446_1f3fd',
  '👆🏾': '1f446_1f3fe',
  '👆🏿': '1f446_1f3ff',
  '👇': '1f447',
  '👇🏻': '1f447_1f3fb',
  '👇🏼': '1f447_1f3fc',
  '👇🏽': '1f447_1f3fd',
  '👇🏾': '1f447_1f3fe',
  '👇🏿': '1f447_1f3ff',
  '🖕': '1f595',
  '🖕🏻': '1f595_1f3fb',
  '🖕🏼': '1f595_1f3fc',
  '🖕🏽': '1f595_1f3fd',
  '🖕🏾': '1f595_1f3fe',
  '🖕🏿': '1f595_1f3ff',
  '✍️': '270d_fe0f',
  '✍🏻': '270d_1f3fb',
  '✍🏼': '270d_1f3fc',
  '✍🏽': '270d_1f3fd',
  '✍🏾': '270d_1f3fe',
  '✍🏿': '270d_1f3ff',
  '🤳': '1f933',
  '🤳🏻': '1f933_1f3fb',
  '🤳🏼': '1f933_1f3fc',
  '🤳🏽': '1f933_1f3fd',
  '🤳🏾': '1f933_1f3fe',
  '🤳🏿': '1f933_1f3ff',
  '🙏': '1f64f',
  '🙏🏻': '1f64f_1f3fb',
  '🙏🏼': '1f64f_1f3fc',
  '🙏🏽': '1f64f_1f3fd',
  '🙏🏾': '1f64f_1f3fe',
  '🙏🏿': '1f64f_1f3ff',
  '💅': '1f485',
  '💅🏻': '1f485_1f3fb',
  '💅🏼': '1f485_1f3fc',
  '💅🏽': '1f485_1f3fd',
  '💅🏾': '1f485_1f3fe',
  '💅🏿': '1f485_1f3ff',
  '🤝': '1f91d',
  '🤝🏻': '1f91d_1f3fb',
  '🫱🏻‍🫲🏼': '1faf1_1f3fb_200d_1faf2_1f3fc',
  '🫱🏻‍🫲🏽': '1faf1_1f3fb_200d_1faf2_1f3fd',
  '🫱🏻‍🫲🏾': '1faf1_1f3fb_200d_1faf2_1f3fe',
  '🫱🏻‍🫲🏿': '1faf1_1f3fb_200d_1faf2_1f3ff',
  '🫱🏼‍🫲🏻': '1faf1_1f3fc_200d_1faf2_1f3fb',
  '🤝🏼': '1f91d_1f3fc',
  '🫱🏼‍🫲🏽': '1faf1_1f3fc_200d_1faf2_1f3fd',
  '🫱🏼‍🫲🏾': '1faf1_1f3fc_200d_1faf2_1f3fe',
  '🫱🏼‍🫲🏿': '1faf1_1f3fc_200d_1faf2_1f3ff',
  '🫱🏽‍🫲🏻': '1faf1_1f3fd_200d_1faf2_1f3fb',
  '🫱🏽‍🫲🏼': '1faf1_1f3fd_200d_1faf2_1f3fc',
  '🤝🏽': '1f91d_1f3fd',
  '🫱🏽‍🫲🏾': '1faf1_1f3fd_200d_1faf2_1f3fe',
  '🫱🏽‍🫲🏿': '1faf1_1f3fd_200d_1faf2_1f3ff',
  '🫱🏾‍🫲🏻': '1faf1_1f3fe_200d_1faf2_1f3fb',
  '🫱🏾‍🫲🏼': '1faf1_1f3fe_200d_1faf2_1f3fc',
  '🫱🏾‍🫲🏽': '1faf1_1f3fe_200d_1faf2_1f3fd',
  '🤝🏾': '1f91d_1f3fe',
  '🫱🏾‍🫲🏿': '1faf1_1f3fe_200d_1faf2_1f3ff',
  '🫱🏿‍🫲🏻': '1faf1_1f3ff_200d_1faf2_1f3fb',
  '🫱🏿‍🫲🏼': '1faf1_1f3ff_200d_1faf2_1f3fc',
  '🫱🏿‍🫲🏽': '1faf1_1f3ff_200d_1faf2_1f3fd',
  '🫱🏿‍🫲🏾': '1faf1_1f3ff_200d_1faf2_1f3fe',
  '🤝🏿': '1f91d_1f3ff',
  '🪂': '1fa82',
  '🫈': '1fac8',
  '💃': '1f483',
  '💃🏻': '1f483_1f3fb',
  '💃🏼': '1f483_1f3fc',
  '💃🏽': '1f483_1f3fd',
  '💃🏾': '1f483_1f3fe',
  '💃🏿': '1f483_1f3ff',
  '💐': '1f490',
  '🌹': '1f339',
  '🥀': '1f940',
  '🌷': '1f337',
  '🪷': '1fab7',
  '🌸': '1f338',
  '🪻': '1fabb',
  '🌼': '1f33c',
  '🍂': '1f342',
  '🍁': '1f341',
  '🍄': '1f344',
  '🌿': '1f33f',
  '🌱': '1f331',
  '🍃': '1f343',
  '🍀': '1f340',
  '🌵': '1f335',
  '🪾': '1fabe',
  '🌲': '1f332',
  '🪨': '1faa8',
  '🛘': '1f6d8',
  '🌋': '1f30b',
  '🏞️': '1f3de_fe0f',
  '🌅': '1f305',
  '🌄': '1f304',
  '🌊': '1f30a',
  '🌬️': '1f32c_fe0f',
  '❄️': '2744_fe0f',
  '🌀': '1f300',
  '🌪️': '1f32a_fe0f',
  '🌈': '1f308',
  '💧': '1f4a7',
  '☁️': '2601_fe0f',
  '🌧️': '1f327_fe0f',
  '🌩️': '1f329_fe0f',
  '⛅': '26c5',
  '🪐': '1fa90',
  '🌍': '1f30d',
  '🌎': '1f30e',
  '🌏': '1f30f',
  '🌌': '1f30c',
  '☄️': '2604_fe0f',
  '🦁': '1f981',
  '🐺': '1f43a',
  '🐻': '1f43b',
  '🐼': '1f43c',
  '🦊': '1f98a',
  '🐮': '1f42e',
  '🦄': '1f984',
  '🦎': '1f98e',
  '🐉': '1f409',
  '🦖': '1f996',
  '🦕': '1f995',
  '🐢': '1f422',
  '🐊': '1f40a',
  '🐍': '1f40d',
  '🐸': '1f438',
  '🐇': '1f407',
  '🐀': '1f400',
  '🐩': '1f429',
  '🐕': '1f415',
  '🦮': '1f9ae',
  '🐕‍🦺': '1f415_200d_1f9ba',
  '🐖': '1f416',
  '🐎': '1f40e',
  '🫏': '1facf',
  '🐂': '1f402',
  '🐐': '1f410',
  '🦥': '1f9a5',
  '🦘': '1f998',
  '🐅': '1f405',
  '🐒': '1f412',
  '🦍': '1f98d',
  '🦧': '1f9a7',
  '🐿️': '1f43f_fe0f',
  '🦝': '1f99d',
  '🦔': '1f994',
  '🦦': '1f9a6',
  '🦇': '1f987',
  '🐦': '1f426',
  '🐦‍⬛': '1f426_200d_2b1b',
  '🐓': '1f413',
  '🐣': '1f423',
  '🐤': '1f424',
  '🐥': '1f425',
  '🦅': '1f985',
  '🦉': '1f989',
  '🕊️': '1f54a_fe0f',
  '🪿': '1fabf',
  '🦩': '1f9a9',
  '🦚': '1f99a',
  '🐦‍🔥': '1f426_200d_1f525',
  '🐧': '1f427',
  '🦭': '1f9ad',
  '🦈': '1f988',
  '🫍': '1facd',
  '🐬': '1f42c',
  '🐳': '1f433',
  '🐟': '1f41f',
  '🐡': '1f421',
  '🦞': '1f99e',
  '🦀': '1f980',
  '🐙': '1f419',
  '🪼': '1fabc',
  '🫧': '1fae7',
  '🦂': '1f982',
  '🕷️': '1f577_fe0f',
  '🐌': '1f40c',
  '🐜': '1f41c',
  '🦗': '1f997',
  '🦟': '1f99f',
  '🪳': '1fab3',
  '🪰': '1fab0',
  '🐝': '1f41d',
  '🐞': '1f41e',
  '🦋': '1f98b',
  '🐛': '1f41b',
  '🪱': '1fab1',
  '🐾': '1f43e',
  '🍓': '1f353',
  '🍒': '1f352',
  '🍎': '1f34e',
  '🍅': '1f345',
  '🍉': '1f349',
  '🍊': '1f34a',
  '🥕': '1f955',
  '🥭': '1f96d',
  '🍍': '1f34d',
  '🌽': '1f33d',
  '🍋': '1f34b',
  '🍈': '1f348',
  '🍐': '1f350',
  '🫛': '1fadb',
  '🥬': '1f96c',
  '🫑': '1fad1',
  '🥝': '1f95d',
  '🥑': '1f951',
  '🥦': '1f966',
  '🥒': '1f952',
  '🫐': '1fad0',
  '🍇': '1f347',
  '🫜': '1fadc',
  '🥔': '1f954',
  '🧅': '1f9c5',
  '🫚': '1fada',
  '🧄': '1f9c4',
  '🫘': '1fad8',
  '🍞': '1f35e',
  '🥞': '1f95e',
  '🍳': '1f373',
  '🧀': '1f9c0',
  '🥓': '1f953',
  '🍗': '1f357',
  '🍔': '1f354',
  '🌭': '1f32d',
  '🥨': '1f968',
  '🍕': '1f355',
  '🌮': '1f32e',
  '🌯': '1f32f',
  '🍝': '1f35d',
  '🥗': '1f957',
  '🍜': '1f35c',
  '🍢': '1f362',
  '🍡': '1f361',
  '🍨': '1f368',
  '🍦': '1f366',
  '🥧': '1f967',
  '🍩': '1f369',
  '🍪': '1f36a',
  '🧂': '1f9c2',
  '🍿': '1f37f',
  '🧋': '1f9cb',
  '🧃': '1f9c3',
  '🍼': '1f37c',
  '🍵': '1f375',
  '☕': '2615',
  '🫖': '1fad6',
  '🧉': '1f9c9',
  '🍻': '1f37b',
  '🥂': '1f942',
  '🍾': '1f37e',
  '🍷': '1f377',
  '🫗': '1fad7',
  '🍹': '1f379',
  '🥢': '1f962',
  '🍽️': '1f37d_fe0f',
  '🛑': '1f6d1',
  '🚧': '1f6a7',
  '🚨': '1f6a8',
  '⛽': '26fd',
  '🛟': '1f6df',
  '⚓': '2693',
  '🚦': '1f6a6',
  '🚲': '1f6b2',
  '🏍️': '1f3cd_fe0f',
  '🚗': '1f697',
  '🚚': '1f69a',
  '🚜': '1f69c',
  '🏎️': '1f3ce_fe0f',
  '🚕': '1f695',
  '🚌': '1f68c',
  '🚂': '1f682',
  '⛵': '26f5',
  '🛶': '1f6f6',
  '🛸': '1f6f8',
  '🚀': '1f680',
  '✈️': '2708_fe0f',
  '🛫': '1f6eb',
  '🛬': '1f6ec',
  '🎢': '1f3a2',
  '🎡': '1f3a1',
  '🎠': '1f3a0',
  '🗿': '1f5ff',
  '🏚️': '1f3da_fe0f',
  '🏠': '1f3e0',
  '🏕️': '1f3d5_fe0f',
  '🌇': '1f307',
  '🎈': '1f388',
  '🎂': '1f382',
  '🎁': '1f381',
  '🎆': '1f386',
  '🪔': '1fa94',
  '🪅': '1fa85',
  '🪩': '1faa9',
  '🥇': '1f947',
  '🥈': '1f948',
  '🥉': '1f949',
  '🏆': '1f3c6',
  '⚽': '26bd',
  '⚾': '26be',
  '🥎': '1f94e',
  '🏀': '1f3c0',
  '🏉': '1f3c9',
  '🎾': '1f3be',
  '🏸': '1f3f8',
  '🥍': '1f94d',
  '🏏': '1f3cf',
  '🏑': '1f3d1',
  '🏒': '1f3d2',
  '🎿': '1f3bf',
  '⛸️': '26f8_fe0f',
  '🛼': '1f6fc',
  '🩰': '1fa70',
  '🛹': '1f6f9',
  '⛳': '26f3',
  '🎯': '1f3af',
  '🥏': '1f94f',
  '🪃': '1fa83',
  '🪁': '1fa81',
  '🎣': '1f3a3',
  '🥋': '1f94b',
  '🎱': '1f3b1',
  '🏓': '1f3d3',
  '🎳': '1f3b3',
  '♟️': '265f_fe0f',
  '🎲': '1f3b2',
  '🎰': '1f3b0',
  '🪄': '1fa84',
  '📷': '1f4f7',
  '📸': '1f4f8',
  '🫟': '1fadf',
  '🎷': '1f3b7',
  '🎺': '1f3ba',
  '🪊': '1fa8a',
  '🎸': '1f3b8',
  '🪕': '1fa95',
  '🎻': '1f3bb',
  '🪉': '1fa89',
  '🥁': '1f941',
  '🪇': '1fa87',
  '📺': '1f4fa',
  '🎞️': '1f39e_fe0f',
  '🎬': '1f3ac',
  '🎭': '1f3ad',
  '🎟️': '1f39f_fe0f',
  '📟': '1f4df',
  '🔌': '1f50c',
  '🔋': '1f50b',
  '🪫': '1faab',
  '💿': '1f4bf',
  '💻': '1f4bb',
  '🖨️': '1f5a8_fe0f',
  '🪎': '1fa8e',
  '🪙': '1fa99',
  '💎': '1f48e',
  '💸': '1f4b8',
  '⚖️': '2696_fe0f',
  '🛒': '1f6d2',
  '💡': '1f4a1',
  '🧹': '1f9f9',
  '🧦': '1f9e6',
  '🎓': '1f393',
  '👑': '1f451',
  '💍': '1f48d',
  '🪭': '1faad',
  '☂️': '2602_fe0f',
  '👠': '1f460',
  '👟': '1f45f',
  '🌡️': '1f321_fe0f',
  '🩺': '1fa7a',
  '🛠️': '1f6e0_fe0f',
  '🪏': '1fa8f',
  '⚙️': '2699_fe0f',
  '⛓️‍💥': '26d3_fe0f_200d_1f4a5',
  '⛓️': '26d3_fe0f',
  '🖇️': '1f587_fe0f',
  '✂️': '2702_fe0f',
  '✏️': '270f_fe0f',
  '📚': '1f4da',
  '📊': '1f4ca',
  '📈': '1f4c8',
  '📉': '1f4c9',
  '🗑️': '1f5d1_fe0f',
  '📦': '1f4e6',
  '🗳️': '1f5f3_fe0f',
  '⏰': '23f0',
  '⌛': '231b',
  '⏳': '23f3',
  '🛎️': '1f6ce_fe0f',
  '🔔': '1f514',
  '📣': '1f4e3',
  '🔎': '1f50e',
  '🔮': '1f52e',
  '💣': '1f4a3',
  '🪤': '1faa4',
  '🔒': '1f512',
  '♠️': '2660_fe0f',
  '♈': '2648',
  '♉': '2649',
  '♊': '264a',
  '♋': '264b',
  '♌': '264c',
  '♍': '264d',
  '♎': '264e',
  '♏': '264f',
  '♐': '2650',
  '♑': '2651',
  '♒': '2652',
  '♓': '2653',
  '⛎': '26ce',
  '🗯️': '1f5ef_fe0f',
  '💬': '1f4ac',
  '❗': '2757',
  '❓': '2753',
  '⁉️': '2049_fe0f',
  '‼️': '203c_fe0f',
  '❌': '274c',
  '🆘': '1f198',
  '♨️': '2668_fe0f',
  '📴': '1f4f4',
  '☢️': '2622_fe0f',
  '☣️': '2623_fe0f',
  '⚠️': '26a0_fe0f',
  '✅': '2705',
  '🆕': '1f195',
  '🆓': '1f193',
  '🆙': '1f199',
  '🆗': '1f197',
  '🆒': '1f192',
  '🚮': '1f6ae',
  '☮️': '262e_fe0f',
  '☯️': '262f_fe0f',
  '♾️': '267e_fe0f',
  '🎶': '1f3b6',
  '➕': '2795',
  '©️': 'a9_fe0f',
  '®️': 'ae_fe0f',
  '™️': '2122_fe0f',
  '🏁': '1f3c1',
  '🚩': '1f6a9',
  '🏴': '1f3f4',
  '🏳️': '1f3f3_fe0f',
};

/// Emoji char → category slug from the upstream manifest. Used by the
/// reactions picker to group emojis into sections.
const Map<String, String> kDesktopNotoCategories = <String, String>{
  '😀': 'smileys_and_emotions',
  '😃': 'smileys_and_emotions',
  '😄': 'smileys_and_emotions',
  '😁': 'smileys_and_emotions',
  '😆': 'smileys_and_emotions',
  '😅': 'smileys_and_emotions',
  '😂': 'smileys_and_emotions',
  '🤣': 'smileys_and_emotions',
  '😭': 'smileys_and_emotions',
  '😉': 'smileys_and_emotions',
  '😗': 'smileys_and_emotions',
  '😙': 'smileys_and_emotions',
  '😚': 'smileys_and_emotions',
  '😘': 'smileys_and_emotions',
  '🥰': 'smileys_and_emotions',
  '😍': 'smileys_and_emotions',
  '🤩': 'smileys_and_emotions',
  '🥳': 'smileys_and_emotions',
  '🫠': 'smileys_and_emotions',
  '🙃': 'smileys_and_emotions',
  '🙂': 'smileys_and_emotions',
  '🥲': 'smileys_and_emotions',
  '🥹': 'smileys_and_emotions',
  '😊': 'smileys_and_emotions',
  '☺️': 'smileys_and_emotions',
  '😌': 'smileys_and_emotions',
  '🙂‍↕️': 'smileys_and_emotions',
  '🙂‍↔️': 'smileys_and_emotions',
  '😏': 'smileys_and_emotions',
  '🤤': 'smileys_and_emotions',
  '😋': 'smileys_and_emotions',
  '😛': 'smileys_and_emotions',
  '😝': 'smileys_and_emotions',
  '😜': 'smileys_and_emotions',
  '🤪': 'smileys_and_emotions',
  '🫪': 'smileys_and_emotions',
  '😔': 'smileys_and_emotions',
  '🥺': 'smileys_and_emotions',
  '😬': 'smileys_and_emotions',
  '😑': 'smileys_and_emotions',
  '😐': 'smileys_and_emotions',
  '😶': 'smileys_and_emotions',
  '😶‍🌫️': 'smileys_and_emotions',
  '🫥': 'smileys_and_emotions',
  '🤐': 'smileys_and_emotions',
  '🫡': 'smileys_and_emotions',
  '🤔': 'smileys_and_emotions',
  '🤫': 'smileys_and_emotions',
  '🫢': 'smileys_and_emotions',
  '🤭': 'smileys_and_emotions',
  '🥱': 'smileys_and_emotions',
  '🤗': 'smileys_and_emotions',
  '🫣': 'smileys_and_emotions',
  '😱': 'smileys_and_emotions',
  '🤨': 'smileys_and_emotions',
  '🧐': 'smileys_and_emotions',
  '😒': 'smileys_and_emotions',
  '🙄': 'smileys_and_emotions',
  '😮‍💨': 'smileys_and_emotions',
  '😤': 'smileys_and_emotions',
  '😠': 'smileys_and_emotions',
  '😡': 'smileys_and_emotions',
  '🤬': 'smileys_and_emotions',
  '😞': 'smileys_and_emotions',
  '😓': 'smileys_and_emotions',
  '😟': 'smileys_and_emotions',
  '😥': 'smileys_and_emotions',
  '😢': 'smileys_and_emotions',
  '☹️': 'smileys_and_emotions',
  '🙁': 'smileys_and_emotions',
  '🫤': 'smileys_and_emotions',
  '😕': 'smileys_and_emotions',
  '😰': 'smileys_and_emotions',
  '😨': 'smileys_and_emotions',
  '😧': 'smileys_and_emotions',
  '😦': 'smileys_and_emotions',
  '😮': 'smileys_and_emotions',
  '😯': 'smileys_and_emotions',
  '😲': 'smileys_and_emotions',
  '😳': 'smileys_and_emotions',
  '🤯': 'smileys_and_emotions',
  '😖': 'smileys_and_emotions',
  '😣': 'smileys_and_emotions',
  '😩': 'smileys_and_emotions',
  '😫': 'smileys_and_emotions',
  '😵': 'smileys_and_emotions',
  '😵‍💫': 'smileys_and_emotions',
  '🫨': 'smileys_and_emotions',
  '🥴': 'smileys_and_emotions',
  '🥵': 'smileys_and_emotions',
  '🥶': 'smileys_and_emotions',
  '🤢': 'smileys_and_emotions',
  '🤮': 'smileys_and_emotions',
  '🫩': 'smileys_and_emotions',
  '😴': 'smileys_and_emotions',
  '😪': 'smileys_and_emotions',
  '🤧': 'smileys_and_emotions',
  '🤒': 'smileys_and_emotions',
  '🤕': 'smileys_and_emotions',
  '😷': 'smileys_and_emotions',
  '🤥': 'smileys_and_emotions',
  '😇': 'smileys_and_emotions',
  '🤠': 'smileys_and_emotions',
  '🤑': 'smileys_and_emotions',
  '🤓': 'smileys_and_emotions',
  '😎': 'smileys_and_emotions',
  '🥸': 'smileys_and_emotions',
  '🤡': 'smileys_and_emotions',
  '💩': 'smileys_and_emotions',
  '😈': 'smileys_and_emotions',
  '👿': 'smileys_and_emotions',
  '👻': 'smileys_and_emotions',
  '💀': 'smileys_and_emotions',
  '🤖': 'smileys_and_emotions',
  '👹': 'smileys_and_emotions',
  '☃️': 'smileys_and_emotions',
  '⛄': 'smileys_and_emotions',
  '👽': 'smileys_and_emotions',
  '👾': 'smileys_and_emotions',
  '🌚': 'smileys_and_emotions',
  '🌝': 'smileys_and_emotions',
  '🌞': 'smileys_and_emotions',
  '🌛': 'smileys_and_emotions',
  '🌜': 'smileys_and_emotions',
  '😺': 'smileys_and_emotions',
  '😸': 'smileys_and_emotions',
  '😹': 'smileys_and_emotions',
  '😻': 'smileys_and_emotions',
  '😼': 'smileys_and_emotions',
  '😽': 'smileys_and_emotions',
  '🙀': 'smileys_and_emotions',
  '😿': 'smileys_and_emotions',
  '😾': 'smileys_and_emotions',
  '🙈': 'smileys_and_emotions',
  '🙉': 'smileys_and_emotions',
  '🙊': 'smileys_and_emotions',
  '⭐': 'smileys_and_emotions',
  '🌟': 'smileys_and_emotions',
  '✨': 'smileys_and_emotions',
  '⚡': 'smileys_and_emotions',
  '💥': 'smileys_and_emotions',
  '🫯': 'smileys_and_emotions',
  '🕳️': 'smileys_and_emotions',
  '🔥': 'smileys_and_emotions',
  '💯': 'smileys_and_emotions',
  '🎉': 'smileys_and_emotions',
  '🎊': 'smileys_and_emotions',
  '❤️': 'smileys_and_emotions',
  '🧡': 'smileys_and_emotions',
  '💛': 'smileys_and_emotions',
  '💚': 'smileys_and_emotions',
  '🩵': 'smileys_and_emotions',
  '💙': 'smileys_and_emotions',
  '💜': 'smileys_and_emotions',
  '🤎': 'smileys_and_emotions',
  '🖤': 'smileys_and_emotions',
  '🩶': 'smileys_and_emotions',
  '🤍': 'smileys_and_emotions',
  '🩷': 'smileys_and_emotions',
  '💘': 'smileys_and_emotions',
  '💝': 'smileys_and_emotions',
  '💖': 'smileys_and_emotions',
  '💗': 'smileys_and_emotions',
  '💓': 'smileys_and_emotions',
  '💞': 'smileys_and_emotions',
  '💕': 'smileys_and_emotions',
  '💌': 'smileys_and_emotions',
  '💟': 'smileys_and_emotions',
  '♥️': 'smileys_and_emotions',
  '❣️': 'smileys_and_emotions',
  '❤️‍🩹': 'smileys_and_emotions',
  '💔': 'smileys_and_emotions',
  '❤️‍🔥': 'smileys_and_emotions',
  '💋': 'smileys_and_emotions',
  '🫂': 'smileys_and_emotions',
  '🗣️': 'smileys_and_emotions',
  '👣': 'smileys_and_emotions',
  '🫆': 'smileys_and_emotions',
  '🧠': 'smileys_and_emotions',
  '🫀': 'smileys_and_emotions',
  '🩸': 'smileys_and_emotions',
  '🦠': 'smileys_and_emotions',
  '🦴': 'smileys_and_emotions',
  '👀': 'smileys_and_emotions',
  '👁️': 'smileys_and_emotions',
  '🫦': 'smileys_and_emotions',
  '👃': 'smileys_and_emotions',
  '👃🏻': 'smileys_and_emotions',
  '👃🏼': 'smileys_and_emotions',
  '👃🏽': 'smileys_and_emotions',
  '👃🏾': 'smileys_and_emotions',
  '👃🏿': 'smileys_and_emotions',
  '👂': 'smileys_and_emotions',
  '👂🏻': 'smileys_and_emotions',
  '👂🏼': 'smileys_and_emotions',
  '👂🏽': 'smileys_and_emotions',
  '👂🏾': 'smileys_and_emotions',
  '👂🏿': 'smileys_and_emotions',
  '🦻': 'smileys_and_emotions',
  '🦻🏻': 'smileys_and_emotions',
  '🦻🏼': 'smileys_and_emotions',
  '🦻🏽': 'smileys_and_emotions',
  '🦻🏾': 'smileys_and_emotions',
  '🦻🏿': 'smileys_and_emotions',
  '🦶': 'smileys_and_emotions',
  '🦶🏻': 'smileys_and_emotions',
  '🦶🏼': 'smileys_and_emotions',
  '🦶🏽': 'smileys_and_emotions',
  '🦶🏾': 'smileys_and_emotions',
  '🦶🏿': 'smileys_and_emotions',
  '🦵': 'smileys_and_emotions',
  '🦵🏻': 'smileys_and_emotions',
  '🦵🏼': 'smileys_and_emotions',
  '🦵🏽': 'smileys_and_emotions',
  '🦵🏾': 'smileys_and_emotions',
  '🦵🏿': 'smileys_and_emotions',
  '🦿': 'smileys_and_emotions',
  '🦾': 'smileys_and_emotions',
  '💪': 'smileys_and_emotions',
  '💪🏻': 'smileys_and_emotions',
  '💪🏼': 'smileys_and_emotions',
  '💪🏽': 'smileys_and_emotions',
  '💪🏾': 'smileys_and_emotions',
  '💪🏿': 'smileys_and_emotions',
  '👏': 'smileys_and_emotions',
  '👏🏻': 'smileys_and_emotions',
  '👏🏼': 'smileys_and_emotions',
  '👏🏽': 'smileys_and_emotions',
  '👏🏾': 'smileys_and_emotions',
  '👏🏿': 'smileys_and_emotions',
  '👍': 'smileys_and_emotions',
  '👍🏻': 'smileys_and_emotions',
  '👍🏼': 'smileys_and_emotions',
  '👍🏽': 'smileys_and_emotions',
  '👍🏾': 'smileys_and_emotions',
  '👍🏿': 'smileys_and_emotions',
  '👎': 'smileys_and_emotions',
  '👎🏻': 'smileys_and_emotions',
  '👎🏼': 'smileys_and_emotions',
  '👎🏽': 'smileys_and_emotions',
  '👎🏾': 'smileys_and_emotions',
  '👎🏿': 'smileys_and_emotions',
  '🫶': 'smileys_and_emotions',
  '🫶🏻': 'smileys_and_emotions',
  '🫶🏼': 'smileys_and_emotions',
  '🫶🏽': 'smileys_and_emotions',
  '🫶🏾': 'smileys_and_emotions',
  '🫶🏿': 'smileys_and_emotions',
  '🙌': 'smileys_and_emotions',
  '🙌🏻': 'smileys_and_emotions',
  '🙌🏼': 'smileys_and_emotions',
  '🙌🏽': 'smileys_and_emotions',
  '🙌🏾': 'smileys_and_emotions',
  '🙌🏿': 'smileys_and_emotions',
  '👐': 'smileys_and_emotions',
  '👐🏻': 'smileys_and_emotions',
  '👐🏼': 'smileys_and_emotions',
  '👐🏽': 'smileys_and_emotions',
  '👐🏾': 'smileys_and_emotions',
  '👐🏿': 'smileys_and_emotions',
  '🤲': 'smileys_and_emotions',
  '🤲🏻': 'smileys_and_emotions',
  '🤲🏼': 'smileys_and_emotions',
  '🤲🏽': 'smileys_and_emotions',
  '🤲🏾': 'smileys_and_emotions',
  '🤲🏿': 'smileys_and_emotions',
  '🤜': 'smileys_and_emotions',
  '🤜🏻': 'smileys_and_emotions',
  '🤜🏼': 'smileys_and_emotions',
  '🤜🏽': 'smileys_and_emotions',
  '🤜🏾': 'smileys_and_emotions',
  '🤜🏿': 'smileys_and_emotions',
  '🤛': 'smileys_and_emotions',
  '🤛🏻': 'smileys_and_emotions',
  '🤛🏼': 'smileys_and_emotions',
  '🤛🏽': 'smileys_and_emotions',
  '🤛🏾': 'smileys_and_emotions',
  '🤛🏿': 'smileys_and_emotions',
  '✊': 'smileys_and_emotions',
  '✊🏻': 'smileys_and_emotions',
  '✊🏼': 'smileys_and_emotions',
  '✊🏽': 'smileys_and_emotions',
  '✊🏾': 'smileys_and_emotions',
  '✊🏿': 'smileys_and_emotions',
  '👊': 'smileys_and_emotions',
  '👊🏻': 'smileys_and_emotions',
  '👊🏼': 'smileys_and_emotions',
  '👊🏽': 'smileys_and_emotions',
  '👊🏾': 'smileys_and_emotions',
  '👊🏿': 'smileys_and_emotions',
  '🫳': 'smileys_and_emotions',
  '🫳🏻': 'smileys_and_emotions',
  '🫳🏼': 'smileys_and_emotions',
  '🫳🏽': 'smileys_and_emotions',
  '🫳🏾': 'smileys_and_emotions',
  '🫳🏿': 'smileys_and_emotions',
  '🫴': 'smileys_and_emotions',
  '🫴🏻': 'smileys_and_emotions',
  '🫴🏼': 'smileys_and_emotions',
  '🫴🏽': 'smileys_and_emotions',
  '🫴🏾': 'smileys_and_emotions',
  '🫴🏿': 'smileys_and_emotions',
  '🫱': 'smileys_and_emotions',
  '🫱🏻': 'smileys_and_emotions',
  '🫱🏼': 'smileys_and_emotions',
  '🫱🏽': 'smileys_and_emotions',
  '🫱🏾': 'smileys_and_emotions',
  '🫱🏿': 'smileys_and_emotions',
  '🫲': 'smileys_and_emotions',
  '🫲🏻': 'smileys_and_emotions',
  '🫲🏼': 'smileys_and_emotions',
  '🫲🏽': 'smileys_and_emotions',
  '🫲🏾': 'smileys_and_emotions',
  '🫲🏿': 'smileys_and_emotions',
  '🫸': 'smileys_and_emotions',
  '🫸🏻': 'smileys_and_emotions',
  '🫸🏼': 'smileys_and_emotions',
  '🫸🏽': 'smileys_and_emotions',
  '🫸🏾': 'smileys_and_emotions',
  '🫸🏿': 'smileys_and_emotions',
  '🫷': 'smileys_and_emotions',
  '🫷🏻': 'smileys_and_emotions',
  '🫷🏼': 'smileys_and_emotions',
  '🫷🏽': 'smileys_and_emotions',
  '🫷🏾': 'smileys_and_emotions',
  '🫷🏿': 'smileys_and_emotions',
  '👋': 'smileys_and_emotions',
  '👋🏻': 'smileys_and_emotions',
  '👋🏼': 'smileys_and_emotions',
  '👋🏽': 'smileys_and_emotions',
  '👋🏾': 'smileys_and_emotions',
  '👋🏿': 'smileys_and_emotions',
  '🤚': 'smileys_and_emotions',
  '🤚🏻': 'smileys_and_emotions',
  '🤚🏼': 'smileys_and_emotions',
  '🤚🏽': 'smileys_and_emotions',
  '🤚🏾': 'smileys_and_emotions',
  '🤚🏿': 'smileys_and_emotions',
  '🖐️': 'smileys_and_emotions',
  '🖐🏻': 'smileys_and_emotions',
  '🖐🏼': 'smileys_and_emotions',
  '🖐🏽': 'smileys_and_emotions',
  '🖐🏾': 'smileys_and_emotions',
  '🖐🏿': 'smileys_and_emotions',
  '✋': 'smileys_and_emotions',
  '✋🏻': 'smileys_and_emotions',
  '✋🏼': 'smileys_and_emotions',
  '✋🏽': 'smileys_and_emotions',
  '✋🏾': 'smileys_and_emotions',
  '✋🏿': 'smileys_and_emotions',
  '🖖': 'smileys_and_emotions',
  '🖖🏻': 'smileys_and_emotions',
  '🖖🏼': 'smileys_and_emotions',
  '🖖🏽': 'smileys_and_emotions',
  '🖖🏾': 'smileys_and_emotions',
  '🖖🏿': 'smileys_and_emotions',
  '🤟': 'smileys_and_emotions',
  '🤟🏻': 'smileys_and_emotions',
  '🤟🏼': 'smileys_and_emotions',
  '🤟🏽': 'smileys_and_emotions',
  '🤟🏾': 'smileys_and_emotions',
  '🤟🏿': 'smileys_and_emotions',
  '🤘': 'smileys_and_emotions',
  '🤘🏻': 'smileys_and_emotions',
  '🤘🏼': 'smileys_and_emotions',
  '🤘🏽': 'smileys_and_emotions',
  '🤘🏾': 'smileys_and_emotions',
  '🤘🏿': 'smileys_and_emotions',
  '✌️': 'smileys_and_emotions',
  '✌🏻': 'smileys_and_emotions',
  '✌🏼': 'smileys_and_emotions',
  '✌🏽': 'smileys_and_emotions',
  '✌🏾': 'smileys_and_emotions',
  '✌🏿': 'smileys_and_emotions',
  '🤞': 'smileys_and_emotions',
  '🤞🏻': 'smileys_and_emotions',
  '🤞🏼': 'smileys_and_emotions',
  '🤞🏽': 'smileys_and_emotions',
  '🤞🏾': 'smileys_and_emotions',
  '🤞🏿': 'smileys_and_emotions',
  '🫰': 'smileys_and_emotions',
  '🫰🏻': 'smileys_and_emotions',
  '🫰🏼': 'smileys_and_emotions',
  '🫰🏽': 'smileys_and_emotions',
  '🫰🏾': 'smileys_and_emotions',
  '🫰🏿': 'smileys_and_emotions',
  '🤙': 'smileys_and_emotions',
  '🤙🏻': 'smileys_and_emotions',
  '🤙🏼': 'smileys_and_emotions',
  '🤙🏽': 'smileys_and_emotions',
  '🤙🏾': 'smileys_and_emotions',
  '🤙🏿': 'smileys_and_emotions',
  '🤌': 'smileys_and_emotions',
  '🤌🏻': 'smileys_and_emotions',
  '🤌🏼': 'smileys_and_emotions',
  '🤌🏽': 'smileys_and_emotions',
  '🤌🏾': 'smileys_and_emotions',
  '🤌🏿': 'smileys_and_emotions',
  '🤏': 'smileys_and_emotions',
  '🤏🏻': 'smileys_and_emotions',
  '🤏🏼': 'smileys_and_emotions',
  '🤏🏽': 'smileys_and_emotions',
  '🤏🏾': 'smileys_and_emotions',
  '🤏🏿': 'smileys_and_emotions',
  '👌': 'smileys_and_emotions',
  '👌🏻': 'smileys_and_emotions',
  '👌🏼': 'smileys_and_emotions',
  '👌🏽': 'smileys_and_emotions',
  '👌🏾': 'smileys_and_emotions',
  '👌🏿': 'smileys_and_emotions',
  '🫵': 'smileys_and_emotions',
  '🫵🏻': 'smileys_and_emotions',
  '🫵🏼': 'smileys_and_emotions',
  '🫵🏽': 'smileys_and_emotions',
  '🫵🏾': 'smileys_and_emotions',
  '🫵🏿': 'smileys_and_emotions',
  '👉': 'smileys_and_emotions',
  '👉🏻': 'smileys_and_emotions',
  '👉🏼': 'smileys_and_emotions',
  '👉🏽': 'smileys_and_emotions',
  '👉🏾': 'smileys_and_emotions',
  '👉🏿': 'smileys_and_emotions',
  '👈': 'smileys_and_emotions',
  '👈🏻': 'smileys_and_emotions',
  '👈🏼': 'smileys_and_emotions',
  '👈🏽': 'smileys_and_emotions',
  '👈🏾': 'smileys_and_emotions',
  '👈🏿': 'smileys_and_emotions',
  '☝️': 'smileys_and_emotions',
  '☝🏻': 'smileys_and_emotions',
  '☝🏼': 'smileys_and_emotions',
  '☝🏽': 'smileys_and_emotions',
  '☝🏾': 'smileys_and_emotions',
  '☝🏿': 'smileys_and_emotions',
  '👆': 'smileys_and_emotions',
  '👆🏻': 'smileys_and_emotions',
  '👆🏼': 'smileys_and_emotions',
  '👆🏽': 'smileys_and_emotions',
  '👆🏾': 'smileys_and_emotions',
  '👆🏿': 'smileys_and_emotions',
  '👇': 'smileys_and_emotions',
  '👇🏻': 'smileys_and_emotions',
  '👇🏼': 'smileys_and_emotions',
  '👇🏽': 'smileys_and_emotions',
  '👇🏾': 'smileys_and_emotions',
  '👇🏿': 'smileys_and_emotions',
  '🖕': 'smileys_and_emotions',
  '🖕🏻': 'smileys_and_emotions',
  '🖕🏼': 'smileys_and_emotions',
  '🖕🏽': 'smileys_and_emotions',
  '🖕🏾': 'smileys_and_emotions',
  '🖕🏿': 'smileys_and_emotions',
  '✍️': 'smileys_and_emotions',
  '✍🏻': 'smileys_and_emotions',
  '✍🏼': 'smileys_and_emotions',
  '✍🏽': 'smileys_and_emotions',
  '✍🏾': 'smileys_and_emotions',
  '✍🏿': 'smileys_and_emotions',
  '🤳': 'smileys_and_emotions',
  '🤳🏻': 'smileys_and_emotions',
  '🤳🏼': 'smileys_and_emotions',
  '🤳🏽': 'smileys_and_emotions',
  '🤳🏾': 'smileys_and_emotions',
  '🤳🏿': 'smileys_and_emotions',
  '🙏': 'smileys_and_emotions',
  '🙏🏻': 'smileys_and_emotions',
  '🙏🏼': 'smileys_and_emotions',
  '🙏🏽': 'smileys_and_emotions',
  '🙏🏾': 'smileys_and_emotions',
  '🙏🏿': 'smileys_and_emotions',
  '💅': 'smileys_and_emotions',
  '💅🏻': 'smileys_and_emotions',
  '💅🏼': 'smileys_and_emotions',
  '💅🏽': 'smileys_and_emotions',
  '💅🏾': 'smileys_and_emotions',
  '💅🏿': 'smileys_and_emotions',
  '🤝': 'smileys_and_emotions',
  '🤝🏻': 'smileys_and_emotions',
  '🫱🏻‍🫲🏼': 'smileys_and_emotions',
  '🫱🏻‍🫲🏽': 'smileys_and_emotions',
  '🫱🏻‍🫲🏾': 'smileys_and_emotions',
  '🫱🏻‍🫲🏿': 'smileys_and_emotions',
  '🫱🏼‍🫲🏻': 'smileys_and_emotions',
  '🤝🏼': 'smileys_and_emotions',
  '🫱🏼‍🫲🏽': 'smileys_and_emotions',
  '🫱🏼‍🫲🏾': 'smileys_and_emotions',
  '🫱🏼‍🫲🏿': 'smileys_and_emotions',
  '🫱🏽‍🫲🏻': 'smileys_and_emotions',
  '🫱🏽‍🫲🏼': 'smileys_and_emotions',
  '🤝🏽': 'smileys_and_emotions',
  '🫱🏽‍🫲🏾': 'smileys_and_emotions',
  '🫱🏽‍🫲🏿': 'smileys_and_emotions',
  '🫱🏾‍🫲🏻': 'smileys_and_emotions',
  '🫱🏾‍🫲🏼': 'smileys_and_emotions',
  '🫱🏾‍🫲🏽': 'smileys_and_emotions',
  '🤝🏾': 'smileys_and_emotions',
  '🫱🏾‍🫲🏿': 'smileys_and_emotions',
  '🫱🏿‍🫲🏻': 'smileys_and_emotions',
  '🫱🏿‍🫲🏼': 'smileys_and_emotions',
  '🫱🏿‍🫲🏽': 'smileys_and_emotions',
  '🫱🏿‍🫲🏾': 'smileys_and_emotions',
  '🤝🏿': 'smileys_and_emotions',
  '🪂': 'people',
  '🫈': 'people',
  '💃': 'people',
  '💃🏻': 'people',
  '💃🏼': 'people',
  '💃🏽': 'people',
  '💃🏾': 'people',
  '💃🏿': 'people',
  '💐': 'animals_and_nature',
  '🌹': 'animals_and_nature',
  '🥀': 'animals_and_nature',
  '🌷': 'animals_and_nature',
  '🪷': 'animals_and_nature',
  '🌸': 'animals_and_nature',
  '🪻': 'animals_and_nature',
  '🌼': 'animals_and_nature',
  '🍂': 'animals_and_nature',
  '🍁': 'animals_and_nature',
  '🍄': 'animals_and_nature',
  '🌿': 'animals_and_nature',
  '🌱': 'animals_and_nature',
  '🍃': 'animals_and_nature',
  '🍀': 'animals_and_nature',
  '🌵': 'animals_and_nature',
  '🪾': 'animals_and_nature',
  '🌲': 'animals_and_nature',
  '🪨': 'animals_and_nature',
  '🛘': 'animals_and_nature',
  '🌋': 'animals_and_nature',
  '🏞️': 'animals_and_nature',
  '🌅': 'animals_and_nature',
  '🌄': 'animals_and_nature',
  '🌊': 'animals_and_nature',
  '🌬️': 'animals_and_nature',
  '❄️': 'animals_and_nature',
  '🌀': 'animals_and_nature',
  '🌪️': 'animals_and_nature',
  '🌈': 'animals_and_nature',
  '💧': 'animals_and_nature',
  '☁️': 'animals_and_nature',
  '🌧️': 'animals_and_nature',
  '🌩️': 'animals_and_nature',
  '⛅': 'animals_and_nature',
  '🪐': 'animals_and_nature',
  '🌍': 'animals_and_nature',
  '🌎': 'animals_and_nature',
  '🌏': 'animals_and_nature',
  '🌌': 'animals_and_nature',
  '☄️': 'animals_and_nature',
  '🦁': 'animals_and_nature',
  '🐺': 'animals_and_nature',
  '🐻': 'animals_and_nature',
  '🐼': 'animals_and_nature',
  '🦊': 'animals_and_nature',
  '🐮': 'animals_and_nature',
  '🦄': 'animals_and_nature',
  '🦎': 'animals_and_nature',
  '🐉': 'animals_and_nature',
  '🦖': 'animals_and_nature',
  '🦕': 'animals_and_nature',
  '🐢': 'animals_and_nature',
  '🐊': 'animals_and_nature',
  '🐍': 'animals_and_nature',
  '🐸': 'animals_and_nature',
  '🐇': 'animals_and_nature',
  '🐀': 'animals_and_nature',
  '🐩': 'animals_and_nature',
  '🐕': 'animals_and_nature',
  '🦮': 'animals_and_nature',
  '🐕‍🦺': 'animals_and_nature',
  '🐖': 'animals_and_nature',
  '🐎': 'animals_and_nature',
  '🫏': 'animals_and_nature',
  '🐂': 'animals_and_nature',
  '🐐': 'animals_and_nature',
  '🦥': 'animals_and_nature',
  '🦘': 'animals_and_nature',
  '🐅': 'animals_and_nature',
  '🐒': 'animals_and_nature',
  '🦍': 'animals_and_nature',
  '🦧': 'animals_and_nature',
  '🐿️': 'animals_and_nature',
  '🦝': 'animals_and_nature',
  '🦔': 'animals_and_nature',
  '🦦': 'animals_and_nature',
  '🦇': 'animals_and_nature',
  '🐦': 'animals_and_nature',
  '🐦‍⬛': 'animals_and_nature',
  '🐓': 'animals_and_nature',
  '🐣': 'animals_and_nature',
  '🐤': 'animals_and_nature',
  '🐥': 'animals_and_nature',
  '🦅': 'animals_and_nature',
  '🦉': 'animals_and_nature',
  '🕊️': 'animals_and_nature',
  '🪿': 'animals_and_nature',
  '🦩': 'animals_and_nature',
  '🦚': 'animals_and_nature',
  '🐦‍🔥': 'animals_and_nature',
  '🐧': 'animals_and_nature',
  '🦭': 'animals_and_nature',
  '🦈': 'animals_and_nature',
  '🫍': 'animals_and_nature',
  '🐬': 'animals_and_nature',
  '🐳': 'animals_and_nature',
  '🐟': 'animals_and_nature',
  '🐡': 'animals_and_nature',
  '🦞': 'animals_and_nature',
  '🦀': 'animals_and_nature',
  '🐙': 'animals_and_nature',
  '🪼': 'animals_and_nature',
  '🫧': 'animals_and_nature',
  '🦂': 'animals_and_nature',
  '🕷️': 'animals_and_nature',
  '🐌': 'animals_and_nature',
  '🐜': 'animals_and_nature',
  '🦗': 'animals_and_nature',
  '🦟': 'animals_and_nature',
  '🪳': 'animals_and_nature',
  '🪰': 'animals_and_nature',
  '🐝': 'animals_and_nature',
  '🐞': 'animals_and_nature',
  '🦋': 'animals_and_nature',
  '🐛': 'animals_and_nature',
  '🪱': 'animals_and_nature',
  '🐾': 'animals_and_nature',
  '🍓': 'food_and_drink',
  '🍒': 'food_and_drink',
  '🍎': 'food_and_drink',
  '🍅': 'food_and_drink',
  '🍉': 'food_and_drink',
  '🍊': 'food_and_drink',
  '🥕': 'food_and_drink',
  '🥭': 'food_and_drink',
  '🍍': 'food_and_drink',
  '🌽': 'food_and_drink',
  '🍋': 'food_and_drink',
  '🍈': 'food_and_drink',
  '🍐': 'food_and_drink',
  '🫛': 'food_and_drink',
  '🥬': 'food_and_drink',
  '🫑': 'food_and_drink',
  '🥝': 'food_and_drink',
  '🥑': 'food_and_drink',
  '🥦': 'food_and_drink',
  '🥒': 'food_and_drink',
  '🫐': 'food_and_drink',
  '🍇': 'food_and_drink',
  '🫜': 'food_and_drink',
  '🥔': 'food_and_drink',
  '🧅': 'food_and_drink',
  '🫚': 'food_and_drink',
  '🧄': 'food_and_drink',
  '🫘': 'food_and_drink',
  '🍞': 'food_and_drink',
  '🥞': 'food_and_drink',
  '🍳': 'food_and_drink',
  '🧀': 'food_and_drink',
  '🥓': 'food_and_drink',
  '🍗': 'food_and_drink',
  '🍔': 'food_and_drink',
  '🌭': 'food_and_drink',
  '🥨': 'food_and_drink',
  '🍕': 'food_and_drink',
  '🌮': 'food_and_drink',
  '🌯': 'food_and_drink',
  '🍝': 'food_and_drink',
  '🥗': 'food_and_drink',
  '🍜': 'food_and_drink',
  '🍢': 'food_and_drink',
  '🍡': 'food_and_drink',
  '🍨': 'food_and_drink',
  '🍦': 'food_and_drink',
  '🥧': 'food_and_drink',
  '🍩': 'food_and_drink',
  '🍪': 'food_and_drink',
  '🧂': 'food_and_drink',
  '🍿': 'food_and_drink',
  '🧋': 'food_and_drink',
  '🧃': 'food_and_drink',
  '🍼': 'food_and_drink',
  '🍵': 'food_and_drink',
  '☕': 'food_and_drink',
  '🫖': 'food_and_drink',
  '🧉': 'food_and_drink',
  '🍻': 'food_and_drink',
  '🥂': 'food_and_drink',
  '🍾': 'food_and_drink',
  '🍷': 'food_and_drink',
  '🫗': 'food_and_drink',
  '🍹': 'food_and_drink',
  '🥢': 'food_and_drink',
  '🍽️': 'food_and_drink',
  '🛑': 'travel_and_places',
  '🚧': 'travel_and_places',
  '🚨': 'travel_and_places',
  '⛽': 'travel_and_places',
  '🛟': 'travel_and_places',
  '⚓': 'travel_and_places',
  '🚦': 'travel_and_places',
  '🚲': 'travel_and_places',
  '🏍️': 'travel_and_places',
  '🚗': 'travel_and_places',
  '🚚': 'travel_and_places',
  '🚜': 'travel_and_places',
  '🏎️': 'travel_and_places',
  '🚕': 'travel_and_places',
  '🚌': 'travel_and_places',
  '🚂': 'travel_and_places',
  '⛵': 'travel_and_places',
  '🛶': 'travel_and_places',
  '🛸': 'travel_and_places',
  '🚀': 'travel_and_places',
  '✈️': 'travel_and_places',
  '🛫': 'travel_and_places',
  '🛬': 'travel_and_places',
  '🎢': 'travel_and_places',
  '🎡': 'travel_and_places',
  '🎠': 'travel_and_places',
  '🗿': 'travel_and_places',
  '🏚️': 'travel_and_places',
  '🏠': 'travel_and_places',
  '🏕️': 'travel_and_places',
  '🌇': 'travel_and_places',
  '🎈': 'activities_and_events',
  '🎂': 'activities_and_events',
  '🎁': 'activities_and_events',
  '🎆': 'activities_and_events',
  '🪔': 'activities_and_events',
  '🪅': 'activities_and_events',
  '🪩': 'activities_and_events',
  '🥇': 'activities_and_events',
  '🥈': 'activities_and_events',
  '🥉': 'activities_and_events',
  '🏆': 'activities_and_events',
  '⚽': 'activities_and_events',
  '⚾': 'activities_and_events',
  '🥎': 'activities_and_events',
  '🏀': 'activities_and_events',
  '🏉': 'activities_and_events',
  '🎾': 'activities_and_events',
  '🏸': 'activities_and_events',
  '🥍': 'activities_and_events',
  '🏏': 'activities_and_events',
  '🏑': 'activities_and_events',
  '🏒': 'activities_and_events',
  '🎿': 'activities_and_events',
  '⛸️': 'activities_and_events',
  '🛼': 'activities_and_events',
  '🩰': 'activities_and_events',
  '🛹': 'activities_and_events',
  '⛳': 'activities_and_events',
  '🎯': 'activities_and_events',
  '🥏': 'activities_and_events',
  '🪃': 'activities_and_events',
  '🪁': 'activities_and_events',
  '🎣': 'activities_and_events',
  '🥋': 'activities_and_events',
  '🎱': 'activities_and_events',
  '🏓': 'activities_and_events',
  '🎳': 'activities_and_events',
  '♟️': 'activities_and_events',
  '🎲': 'activities_and_events',
  '🎰': 'activities_and_events',
  '🪄': 'activities_and_events',
  '📷': 'activities_and_events',
  '📸': 'activities_and_events',
  '🫟': 'activities_and_events',
  '🎷': 'activities_and_events',
  '🎺': 'activities_and_events',
  '🪊': 'activities_and_events',
  '🎸': 'activities_and_events',
  '🪕': 'activities_and_events',
  '🎻': 'activities_and_events',
  '🪉': 'activities_and_events',
  '🥁': 'activities_and_events',
  '🪇': 'activities_and_events',
  '📺': 'activities_and_events',
  '🎞️': 'activities_and_events',
  '🎬': 'activities_and_events',
  '🎭': 'activities_and_events',
  '🎟️': 'activities_and_events',
  '📟': 'objects',
  '🔌': 'objects',
  '🔋': 'objects',
  '🪫': 'objects',
  '💿': 'objects',
  '💻': 'objects',
  '🖨️': 'objects',
  '🪎': 'objects',
  '🪙': 'objects',
  '💎': 'objects',
  '💸': 'objects',
  '⚖️': 'objects',
  '🛒': 'objects',
  '💡': 'objects',
  '🧹': 'objects',
  '🧦': 'objects',
  '🎓': 'objects',
  '👑': 'objects',
  '💍': 'objects',
  '🪭': 'objects',
  '☂️': 'objects',
  '👠': 'objects',
  '👟': 'objects',
  '🌡️': 'objects',
  '🩺': 'objects',
  '🛠️': 'objects',
  '🪏': 'objects',
  '⚙️': 'objects',
  '⛓️‍💥': 'objects',
  '⛓️': 'objects',
  '🖇️': 'objects',
  '✂️': 'objects',
  '✏️': 'objects',
  '📚': 'objects',
  '📊': 'objects',
  '📈': 'objects',
  '📉': 'objects',
  '🗑️': 'objects',
  '📦': 'objects',
  '🗳️': 'objects',
  '⏰': 'objects',
  '⌛': 'objects',
  '⏳': 'objects',
  '🛎️': 'objects',
  '🔔': 'objects',
  '📣': 'objects',
  '🔎': 'objects',
  '🔮': 'objects',
  '💣': 'objects',
  '🪤': 'objects',
  '🔒': 'objects',
  '♠️': 'symbols',
  '♈': 'symbols',
  '♉': 'symbols',
  '♊': 'symbols',
  '♋': 'symbols',
  '♌': 'symbols',
  '♍': 'symbols',
  '♎': 'symbols',
  '♏': 'symbols',
  '♐': 'symbols',
  '♑': 'symbols',
  '♒': 'symbols',
  '♓': 'symbols',
  '⛎': 'symbols',
  '🗯️': 'symbols',
  '💬': 'symbols',
  '❗': 'symbols',
  '❓': 'symbols',
  '⁉️': 'symbols',
  '‼️': 'symbols',
  '❌': 'symbols',
  '🆘': 'symbols',
  '♨️': 'symbols',
  '📴': 'symbols',
  '☢️': 'symbols',
  '☣️': 'symbols',
  '⚠️': 'symbols',
  '✅': 'symbols',
  '🆕': 'symbols',
  '🆓': 'symbols',
  '🆙': 'symbols',
  '🆗': 'symbols',
  '🆒': 'symbols',
  '🚮': 'symbols',
  '☮️': 'symbols',
  '☯️': 'symbols',
  '♾️': 'symbols',
  '🎶': 'symbols',
  '➕': 'symbols',
  '©️': 'symbols',
  '®️': 'symbols',
  '™️': 'symbols',
  '🏁': 'flags',
  '🚩': 'flags',
  '🏴': 'flags',
  '🏳️': 'flags',
};

/// Human-readable Russian display name per category slug — what the
/// picker shows as the section header. Slugs that don't appear in the
/// manifest can be safely added here with a fallback label.
const Map<String, String> kDesktopNotoCategoryLabelsRu = <String, String>{
  'smileys_and_emotions': 'Смайлики и эмоции',
  'people': 'Люди и тело',
  'animals_and_nature': 'Природа',
  'food_and_drink': 'Еда и напитки',
  'travel_and_places': 'Путешествия',
  'activities_and_events': 'Активности',
  'objects': 'Предметы',
  'symbols': 'Символы',
  'flags': 'Флаги',
  'other': 'Прочее',
};

/// Ordered list of category slugs (for left-rail jump order and section
/// rendering order). MUST match the order categories first appear in the
/// upstream manifest so the rail reflects upstream's grouping.
const List<String> kDesktopNotoCategoryOrder = <String>[
  'smileys_and_emotions',
  'people',
  'animals_and_nature',
  'food_and_drink',
  'travel_and_places',
  'activities_and_events',
  'objects',
  'symbols',
  'flags',
];


/// True when [text], stripped of whitespace, is a single emoji that we know
/// how to render via Noto Lottie. The mobile «solo emoji» bubble uses the
/// same gate (`_isSoloNotoEmoji`).
bool isSoloNotoEmoji(String text) {
  final t = text.trim();
  return t.isNotEmpty && kDesktopNotoCodepoints.containsKey(t);
}

/// True if [emoji] has an animated Lottie file we can fetch.
bool isAnimatableNotoEmoji(String emoji) =>
    kDesktopNotoCodepoints.containsKey(emoji.trim());

final Map<String, File> _notoFileCache = <String, File>{};
final Map<String, Future<File?>> _notoLoadFutures = <String, Future<File?>>{};

/// Loads the Lottie JSON file for [emoji] from disk or the Noto CDN. The
/// returned file is cached in memory for the life of the process and on
/// disk in the system temp directory under `noto_emoji_{cp}.json`.
Future<File?> loadNotoLottieFile(String emoji) {
  final codepoint = kDesktopNotoCodepoints[emoji.trim()];
  if (codepoint == null) return Future<File?>.value(null);
  return _notoLoadFutures[codepoint] ??= _doLoadNotoLottie(codepoint);
}

Future<File?> _doLoadNotoLottie(String codepoint) async {
  if (_notoFileCache.containsKey(codepoint)) return _notoFileCache[codepoint];
  try {
    final dir = await getTemporaryDirectory();
    final file = File(p.join(dir.path, 'noto_emoji_$codepoint.json'));
    if (await file.exists()) {
      // Desktop shares the mobile cache filename, but not necessarily the
      // mobile cache: heal a file downloaded before the `tm` + `sr` fix.
      try {
        final healed = normalizeNotoLottieBytes(await file.readAsBytes());
        if (healed != null) await file.writeAsBytes(healed);
      } catch (_) {}
      _notoFileCache[codepoint] = file;
      return file;
    }
    final uri = Uri.parse(
      'https://fonts.gstatic.com/s/e/notoemoji/latest/$codepoint/lottie.json',
    );
    final response =
        await http_pkg.get(uri).timeout(const Duration(seconds: 15));
    if (response.statusCode == 200) {
      final normalized = normalizeNotoLottieBytes(response.bodyBytes);
      await file.writeAsBytes(normalized ?? response.bodyBytes);
      _notoFileCache[codepoint] = file;
      return file;
    }
  } catch (_) {
    // Fall through to null — the caller renders the bare unicode emoji.
  }
  return null;
}

/// How a [NotoEmojiLottie] should play. Mirrors mobile's `_NotoLottieMode`.
enum NotoLottieMode {
  /// First frame only, no ticking. Used in the emoji picker grid.
  preview,

  /// Plays once on mount or on widget-key change, then snaps to frame 0.
  once,

  /// Loops forever. Used by the quick-react bar so the icons feel alive.
  looping,
}

/// Animated Noto emoji rendered via Lottie. Falls back to the bare unicode
/// emoji while the JSON downloads (or forever if the network is offline).
class NotoEmojiLottie extends StatefulWidget {
  const NotoEmojiLottie({
    super.key,
    required this.emoji,
    this.size = 44.0,
    this.mode = NotoLottieMode.looping,
  });

  final String emoji;
  final double size;
  final NotoLottieMode mode;

  @override
  State<NotoEmojiLottie> createState() => _NotoEmojiLottieState();
}

/// Счётчик для неповторяющихся ключей сторожа видимости.
int _notoVisibilitySeq = 0;

class _NotoEmojiLottieState extends State<NotoEmojiLottie>
    with SingleTickerProviderStateMixin {
  File? _file;
  AnimationController? _ctrl;
  int _loadGeneration = 0;

  /// 🔴 БЕСКОНЕЧНОЕ ПРОИГРЫВАНИЕ КРУТИТСЯ, ТОЛЬКО ПОКА ЭМОДЗИ ВИДНО.
  ///
  /// Зацикленная анимация заказывает кадр каждый вsync. Без этого сторожа один
  /// смайлик в тексте держал бы ВСЁ окно в непрерывной перерисовке, а в ленте
  /// на тысячу сообщений таких смайликов сотни — включая уехавшие далеко за
  /// край экрана. Телефон этот урок уже прошёл и сторожит тем же способом.
  ///
  /// Задержка `VisibilityDetector` в 500 мс означает, что при прокрутке это не
  /// дёргается на каждый кадр.
  late final Key _visibilityKey = Key(
    'noto-emoji-vis-${_notoVisibilitySeq++}',
  );
  bool _visible = true;

  void _onVisibilityChanged(VisibilityInfo info) {
    final visible = info.visibleFraction > 0;
    if (visible == _visible) return;
    _visible = visible;
    final ctrl = _ctrl;
    if (ctrl == null || widget.mode != NotoLottieMode.looping) return;
    if (visible) {
      if (!ctrl.isAnimating) ctrl.repeat();
    } else {
      ctrl.stop();
    }
  }

  void _loadEmojiFile(String emoji) {
    final currentGeneration = ++_loadGeneration;
    final codepoint = kDesktopNotoCodepoints[emoji.trim()];
    if (codepoint != null && _notoFileCache.containsKey(codepoint)) {
      _file = _notoFileCache[codepoint];
      return;
    }

    _file = null;
    loadNotoLottieFile(emoji).then((f) {
      if (!mounted || currentGeneration != _loadGeneration) return;
      if (widget.emoji != emoji) return;
      setState(() => _file = f);
    });
  }

  @override
  void initState() {
    super.initState();
    if (widget.mode == NotoLottieMode.looping) {
      // Своим контроллером, а не `repeat: true` у `Lottie.file`: остановить
      // чужой внутренний контроллер, когда эмодзи уехало за край, нечем.
      _ctrl = AnimationController(
        vsync: this,
        duration: const Duration(seconds: 2),
      );
    } else if (widget.mode == NotoLottieMode.once) {
      _ctrl = AnimationController(
        vsync: this,
        duration: const Duration(seconds: 2),
      )..addStatusListener((status) {
          // Some Noto Lottie JSONs end with a transparent frame, so snap
          // back to frame 0 after completion so the emoji stays visible.
          if (status == AnimationStatus.completed && mounted) {
            _ctrl!.value = 0.0;
          }
        });
    }
    _loadEmojiFile(widget.emoji);
  }

  @override
  void didUpdateWidget(covariant NotoEmojiLottie oldWidget) {
    super.didUpdateWidget(oldWidget);
    if (oldWidget.emoji != widget.emoji) {
      setState(() => _file = null);
      _ctrl?.reset();
      _loadEmojiFile(widget.emoji);
      return;
    }
    if (oldWidget.mode != widget.mode && widget.mode == NotoLottieMode.once) {
      _ctrl?.reset();
    }
  }

  @override
  void dispose() {
    _ctrl?.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final f = _file;
    if (f == null) return _fallback();
    switch (widget.mode) {
      case NotoLottieMode.preview:
        return SizedBox(
          width: widget.size,
          height: widget.size,
          child: Lottie.file(
            f,
            width: widget.size,
            height: widget.size,
            animate: false,
            fit: BoxFit.contain,
            errorBuilder: (_, __, ___) => _fallback(),
          ),
        );
      case NotoLottieMode.once:
        final ctrl = _ctrl!;
        return SizedBox(
          width: widget.size,
          height: widget.size,
          child: Lottie.file(
            f,
            width: widget.size,
            height: widget.size,
            controller: ctrl,
            onLoaded: (comp) {
              ctrl.duration = comp.duration;
              if (ctrl.status == AnimationStatus.dismissed) ctrl.forward();
            },
            fit: BoxFit.contain,
            errorBuilder: (_, __, ___) => _fallback(),
          ),
        );
      case NotoLottieMode.looping:
        return VisibilityDetector(
          key: _visibilityKey,
          onVisibilityChanged: _onVisibilityChanged,
          child: SizedBox(
            width: widget.size,
            height: widget.size,
            child: Lottie.file(
              f,
              width: widget.size,
              height: widget.size,
              controller: _ctrl,
              // Часть Noto-анимаций заканчивается прозрачным кадром: крутим
              // почти полный круг, чтобы смайлик не мигал пустотой.
              onLoaded: (comp) {
                final ctrl = _ctrl;
                if (ctrl == null) return;
                ctrl.duration = comp.duration;
                if (_visible && !ctrl.isAnimating) {
                  ctrl.repeat(min: 0.01, max: 0.97, period: comp.duration * 0.96);
                }
              },
              fit: BoxFit.contain,
              errorBuilder: (_, __, ___) => _fallback(),
            ),
          ),
        );
    }
  }

  Widget _fallback() => SizedBox(
        width: widget.size,
        height: widget.size,
        child: Center(
          child: Text(
            widget.emoji,
            style: TextStyle(fontSize: widget.size * 0.72),
            textAlign: TextAlign.center,
          ),
        ),
      );
}
